### ISSUE TITLE
Enable dimming for light on kitchen fan

### ISSUE THREAD

**Issue by corvy** [astrandb/miele#121]
### Feature request

I have a kitchen fan (ventilator) with 4 spots, called DA 2808. These spots are dimmable from the Miele app but in HA it only shows up as a on/off switch. Would it at all be possible to get a dimmable light entity in HA through the API? 

See the below screenshots. 

![Screenshot_20220810-084940](https://user-images.githubusercontent.com/138292/183835249-187fd6f1-e264-4e41-a3ea-46c7a2fbb2a8.jpg)

![Screenshot_20220810-085016_Home Assistant](https://user-images.githubusercontent.com/138292/183834734-6f4a6c9d-1a90-46fc-a331-bb6307ad8dea.jpg)

### What version of the integration are you using?

v 0.0.22

### Additional information

If there is anything I could do to support please let me know :)

**Comment by astrandb** [comment]
Unfortunately the public API only supports on/off for lights - if Miele has not changed it recently.
If you can add a diagnostic download for your hood, I can have a look if there are any signs of dimmer controls in the data.

**Comment by corvy** [comment]
I will try to do just that. It that done with this tool I suspect? 

https://www.miele.co.uk/p/miele-benchmark-programming-tool-3053.htm

**Comment by mundschenk-at** [comment]
> I will try to do just that. It that done with this tool I suspect?
> 
> https://www.miele.co.uk/p/miele-benchmark-programming-tool-3053.htm

No from the device view in your HA.

**Comment by corvy** [comment]
Look at that :) Did not know that existed. Here you go! 

[miele-2b90fc953a44f5b6c5d0cc17fc8ddbb1-Cooker hood-dc166e2dc2229c38850e0f02e83ae071.json.txt](https://github.com/astrandb/miele/files/9357928/miele-2b90fc953a44f5b6c5d0cc17fc8ddbb1-Cooker.hood-dc166e2dc2229c38850e0f02e83ae071.json.txt)

**Comment by astrandb** [comment]
Thank you.
It is as I suspected. The public API only supports on/off for your lights.
