### ISSUE TITLE
Log miele status every minute by blueprint

### ISSUE THREAD

**Issue by rploeg** [astrandb/miele#122]
### The problem

In my logbook, when my miele tumble tryer is off, every minute a logbook message is created by the blueprint:

![image](https://user-images.githubusercontent.com/49752333/184309761-bde690d6-ad9a-4b24-b39b-b3b362892859.png)

Maybe it's an enhancement, but I would expect only status changed, when the tumble tryer for example is switched off. 

### Version of miele integration having the issue?

HACS installation

### Version of Home Assistant Core having the issue?

22.8.3

**Comment by astrandb** [comment]
The logging blueprint was created to assist in debugging some translation issues. It might be a bit too ambitious if left on permanently. I will have a look to see if the spamming can be reduced.

**Comment by rploeg** [comment]
thanks!

**Comment by mundschenk-at** [comment]
You can also [exclude all or certain automations from the logbook](https://www.home-assistant.io/integrations/logbook/) via the `exclude` configuration option.
