### ISSUE TITLE
Add Norwegian translation

### ISSUE THREAD

**Issue by astrandb** [astrandb/miele#123]
### Discussed in https://github.com/astrandb/miele/discussions/118

<div type='discussions-op-text'>

<sup>Originally posted by **palengh** August  6, 2022</sup>
[sensor.no.txt](https://github.com/astrandb/miele/files/9275221/sensor.no.txt)
[no.txt](https://github.com/astrandb/miele/files/9275222/no.txt)

Enjoy :-)

Pål
</div>

**Comment by astrandb** [comment]
@palengh I just realized that `.no` is not supported in Home Assistant. Is this Bokmål? In that case the language suffix should be `.nb`. 
If you confirm I will update and merge.

**Comment by palengh** [comment]
Ues this is bokmål. Sone times er need to define it as 'nb_no'

**Comment by astrandb** [comment]
OK, in Home Assistant the language files should be named `*.nb` for Bokmål and `*.nn` for Nynorsk. I will fix in the PR.
