### ISSUE TITLE
Missing / incorrect program mapping for TCR790WP dryer

### ISSUE THREAD

**Issue by apeeters** [astrandb/miele#127]
### The problem

I noticed that many of the programs of the TCR790WP dryer are missing (number shown), or mapped incorrectly. Some examples:

| Program reported | Actual program |
| ------------------ | --------------- |
| 2                             | Cottons             |
| 9                             | Cottons ECO    |
| 1                             | Automatic extra    |
| Automatic extra    | Smoothing    |

I can provide a PR, but not sure how to handle those differing program mappings.

### Version of miele integration having the issue?

0.0.23

### Version of Home Assistant Core having the issue?

2022.8.6

**Comment by mundschenk-at** [comment]
If you can provide a list program IDs/names (a complete one would be best), I can handle the PR. 

Unfortunately Miele provides no list at all and various reverse engineered online sources are somewhat contradictory. We verified what we could with the available devices.

**Comment by apeeters** [comment]
Sure, here you go:

| Program reported | Actual program EN (UK) |
| ----------------- | ----------------------- |
| 2                             | Cottons             |
| 9                             | Cottons ECO    |
| 3                             | Minimum iron    |
| 5                             | Delicates   |
| gentle_minimum_iron (= 31)  | Bed linen    |
| 1                             | Automatic    |
| 4                             | Wollens handcare    |
| 17                             | Silks handcare    |
| 8                             | Express    |
| 14                             | Shirts    |
| 13                             | Denim    |
| 24                             | Steam care    |
| 15                             | Sportswear    |
| 22                             | Basket programme    |
| 16                             | Outerwear    |
| 12                             | Proofing    |
| 6                             | Timed drying Warm air    |
| 19                             | Standard pillows    |
| 7                             | Timed drying Cool air    |
| cottons (=20)   | Large pillows    |
| 11                             | Cottons hygiene    |
| 9                             | Cottons ECO    |
| automatic_plus (=10)    | Pre-ironing    |

**Comment by mundschenk-at** [comment]
@apeeters Thank you!

@astrandb We seem to have the first overlapping program IDs within a device class. (`10`, `20`, `31`). How should we handle that? Maybe solicit some more input in the forums first, to make sure there is actually overlap and some incorrect lists going around?

**Comment by astrandb** [comment]
@mundschenk-at I think we must make sure that there is a true overlap before we redesign the mapping structure. I would be happy if you could ask around.

**Comment by mamoel666** [comment]
My TEJ675WP (dryer) reports this:

```
1	Automatic plus
2	Cottons
3	Minimum iron
4	Woollens handcare
5	Delicates
6	Warm air
7	Cool air
8	Express
9	Cottons
10	Pre-ironing
12	Proofing
13	Denim
14	Shirts
15	Sportswear
16	Outerwear
17	Silks handcare
19	Standard pillows
22	Basket programme
31	Bed linen
```
2 and 9 are Cottons, but 9 with a ' ' (single space) at the end.

**Comment by mundschenk-at** [comment]
Does your device have "Cottons ECO" (according to the manual/UI), @mamoel666? This might be a bug on Miele's side. I'll try get additional listings from other (older) dryers - they might have changed the numbering for their heat-pump models.

**Comment by apeeters** [comment]
FYI: try different language settings on your machine, i.e. US vs UK make a huge difference.

**Comment by mamoel666** [comment]
I took the names directly from the Miele Swagger-UI.

The manual says:
![image](https://user-images.githubusercontent.com/45948842/186892043-3d9ca674-4f5c-4a3e-b93e-ca99b03e218b.png)

**Comment by astrandb** [comment]
@mundschenk-at If it turns out that there is troublesome overlap of `raw_value` we could change approach for translation.
We could use the returned clear text in default language (en) as index instead of the numeric value. This would be a breaking change for users that use the sensor values in templates or automations, The alternative to maintain separate tables for each device type and version can be an Sisyphean effort over time.

**Comment by mundschenk-at** [comment]
> We could use the returned clear text in default language (en) as index instead of the numeric value. This would be a breaking change for users that use the sensor values in templates or automations, The alternative to maintain separate tables for each device type and version can be an Sisyphean effort over time.

I'm still hoping that any overlap will be "localized" to an easily identifiable subtype (i.e. dryers with `WP` as the last characters of their model number). I'll ask around in the HA forums.

@mamoel666 So `Cottons ` with the space is definitely the ECO variant. Apparently they only identified it by the tag/arrow on this device because it has a physical wheel for program selection (in the German EU energy consumption report it is identified as "Baumwolle mit Pfeil", i.e. "Cottons with arrow").

**Comment by apeeters** [comment]
> Sure, here you go:

For the record: these are the program names I see on the display of the machine, Iin HA, I only noted down the program id.

**Comment by aturri** [comment]
Hi, any update about this topic? I have a TCJ690WP tumble dryer and program names are completely wrong. At the moment I've forked the repository and I'm using my own mappings for the dryer programs.

**Comment by astrandb** [comment]
I have an ongoing discussion with developers at Miele regarding the documentation of program names etc. Will report back here if we can get proper documantation directly from Miele or if we have to do some more reverse engineering.
