### ISSUE TITLE
Dishwasher long term statistics will be suppressed

### ISSUE THREAD

**Issue by neildsb** [astrandb/miele#140]
### The problem

Home Assistant 2022.9.0
Supervisor 2022.08.5
Operating System 8.5
Frontend 20220907.0 - latest

Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:396
Integration: Sensor (documentation, issues)

The unit of sensor.dishwasher_water_consumption (l) does not match the unit of already compiled statistics (L). Generation of long term statistics will be suppressed unless the unit changes back to L. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this

### Version of miele integration having the issue?

v0.0.25

### Version of Home Assistant Core having the issue?

2022.9.0

**Comment by astrandb** [comment]
There has obviously been a change in the database internals in HA in the 220907 version. I have not been able to find any info on this change in the changelog. 
The SI unit "liter" can be abbreviated "l" (lower case) or "L", both variants are correct nowadays. Way back, when I went to school only "l" was regarded as correct.
You can probably fix your problem by going to the link suggested in the error message. However, if the unit in the code is changed from "l" to "L" you may get the same message again. I appeciate any advice how to fix the problem once and for all.

**Comment by ericvb** [comment]
Hi @astrandb,
Now I've the same problem, but in the opposite way, with the latest version of HA and the Miele integration.
Home Assistant 2022.12.9 
Supervisor 2022.12.1 
Operating System 9.4 
Frontend 20221213.1 - latest

`Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:374
Integration: Sensor (documentation, issues)
First occurred: 09:25:10 (1 occurrences)
Last logged: 09:25:10

The unit of sensor.washing_machine_water_consumption (L) can not be converted to the unit of previously compiled statistics (l). Generation of long term statistics will be suppressed unless the unit changes back to l or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this`

Sadly, I also don't know the answer to your question how to fix this problem once and for all.
Maybe contact one of the HA core team members like Frenck?

**Comment by astrandb** [comment]
The integration is using `UnitOfVolume.LITERS` for water consumption since a couple of months. This is the unit that is recommended in HA. If there are old items in the database with "l" you will get the message above.
