### ISSUE TITLE
Washing machine: Incorrect (negative) temperature in cold water program

### ISSUE THREAD

**Issue by davidmh78** [astrandb/miele#143]
### The problem

Hi, in a Miele washing machine (model WWI860) when the water temp for the washing program is set to cold, in HA the target temperature is reported as -327.66 °C (works OK in any other temperature setting). 

Maybe it should be set to 0 °C or N/A if possible.

Thanks!

### Version of miele integration having the issue?

miele-0.0.25

### Version of Home Assistant Core having the issue?

core-2022.10.2

**Comment by astrandb** [comment]
The Miele API uses -327.68 as a marker for unavailable value in certain conditions. I dont recognise -327.66 . If would be very helpful if you can get a diagnostic download from the device page in HA when this erroneous target temperature is displayed. Please upload the downloaded file to this issue.

**Comment by davidmh78** [comment]
Diagnostic attached
[miele-73ac42db612e3ec222d29a38d6c1ef29-Washing machine-41d331ef695a1a5ee2318b356047bbfa.json.txt](https://github.com/astrandb/miele/files/9752931/miele-73ac42db612e3ec222d29a38d6c1ef29-Washing.machine-41d331ef695a1a5ee2318b356047bbfa.json.txt)

**Comment by astrandb** [comment]
Fixed.
Target temp will be displayed as `unknown`
