### ISSUE TITLE
Energy + Water sensors missing for WCE670

### ISSUE THREAD

**Issue by gschmidl** [astrandb/miele#155]
### The problem

Sensors for the Miele WCE670 washing machine (Miele WCE670 WPS TDos Wifi W1, Firmware: 03.88, Hardware: EK037) remain unavailable for use:

![image](https://user-images.githubusercontent.com/20334/200888154-a126e12a-075a-42c2-8747-fcac3747b89b.png)

- sensor.washing_machine_energy_consumption
- sensor.washing_machine_energy_forecast
- sensor.washing_machine_water_consumption
- sensor.washing_machine_water_forecast

Diagnosis file:

[miele-5651835b1b6aa470023addf55981cc48-Washing machine-fb23c63a5ea2b9546b61cce61dd24588.json.txt](https://github.com/astrandb/miele/files/9973170/miele-5651835b1b6aa470023addf55981cc48-Washing.machine-fb23c63a5ea2b9546b61cce61dd24588.json.txt)

Enabling the sensors manually leads to an error when trying to use them in the energy dashboard. 

### Version of miele integration having the issue?

0.1.0

### Version of Home Assistant Core having the issue?

2022.11.2

### Anything in the logs that might be useful for us?

```txt
Nothing obvious in the logs.
```

**Comment by astrandb** [comment]
Your washing machine is not reporting any values for energy or water consumption as stated by this line in the attached diagnostic file.

`"state|ecoFeedback": null,`

**Comment by astrandb** [comment]
Try to run a washing cycle so that the machine reports some data. After an hour or two the statistics should appear in the enrgy panel.

**Comment by gschmidl** [comment]
I'll try, but shouldn't it report "0" instead of "null"?

**Comment by gschmidl** [comment]
Running now and it works - will the sensors go back to "unavailable" when it's done?

```
      "state|ecoFeedback|currentWaterConsumption|unit": "l",
      "state|ecoFeedback|currentWaterConsumption|value": 8.0,
      "state|ecoFeedback|currentEnergyConsumption|unit": "kWh",
      "state|ecoFeedback|currentEnergyConsumption|value": 0.1,
      "state|ecoFeedback|waterForecast": 0.1,
      "state|ecoFeedback|energyForecast": 0.5,
```

**Comment by astrandb** [comment]
Null from the API means "no value". Zero means 0 liters or 0 kWh. This has been discussed in other issues and there are different opinions what is the right way to handle nulls. I have chosen to do minimal translation of API data and display it according to Home Assistant standards.
The sensors will probably go back to unknown when you turn the machine off, but the statistics should still be there.
Let us wait and see. I cannot test myself because my washing-machine is too old.

**Comment by astrandb** [comment]
It was an active decision to keep the eco-feedback sensors disabled in a new installation of the integration. Permanently unavailable sensors give rise to a lot of questions. Unfortunately there is no way to know from the API what models or versions of washing machines or dishwashers that support  eco-feedback data. And as you have seen, even if the machine supports it, that is not reflected in the the API when the appliance is turned off. 
It could be an interesting challenge for me (or anyone else that want to help) to autoenable these sensors  the first time the API starts to report relevant data.

**Comment by rudizl** [comment]
![Screenshot_20221109_201157_Home Assistant](https://user-images.githubusercontent.com/5582186/200910441-5893d38d-fefc-4a77-bcf4-3c0a716f65b1.jpg)
Those are mine values for WCR860 right now. Before starting the program the energy configuration shows errors, now everything seems OK.

**Comment by gschmidl** [comment]
> It was an active decision to keep the eco-feedback sensors disabled in a new installation of the integration. Permanently unavailable sensors give rise to a lot of questions. Unfortunately there is no way to know from the API what models or versions of washing machines or dishwashers that support eco-feedback data. And as you have seen, even if the machine supports it, that is not reflected in the the API when the appliance is turned off. It could be an interesting challenge for me (or anyone else that want to help) to autoenable these sensors the first time the API starts to report relevant data.

That's fair enough - maybe mention it in the documentation? It seems to have worked just fine during the washing cycle just now, which is exactly what I'm looking for. Thank you.
