### ISSUE TITLE
G7910 reports Power Wash as ProgramID=44 

### ISSUE THREAD

**Issue by juliekoubova** [astrandb/miele#157]
### The problem

Hey, first of all, thanks for all this work. It's amazing! On to the bug: I have the G7910 dishwasher, and it seems to report program id 44 when running the Power Wash program. The integration understands this as `glasses_warm`. Are you sure that's correct? Or is it maybe possible different dishwashers use different ids?

Once it completes, I'll try running the glasses program and see what it sends then.

### Version of miele integration having the issue?

0.1.0

### Version of Home Assistant Core having the issue?

2022.11.4

**Comment by juliekoubova** [comment]
cc @the-ress

**Comment by mundschenk-at** [comment]
@astrandb and I were under the impression that each type of device used a a list of IDs that sometimes contained duplicate entries but none that outright conflicted. That was what Miele integrations for other home automation systems used and we tried to expand the lists from available devices. 

Now since his integration has found a wider audience, it appears that this theory is only holds true for older devices. I've been trying to solicit lists program IDs by device on the HA community forums, but with limited response so far. We might need to find another way to model program IDs (personally I'd hate to loose the abstraction level and just display the raw Miele API response, but without a diverse collection of devices with their specific program IDs, there might be no other way.

**Comment by juliekoubova** [comment]
@the-ress had a great idea to look into the Android app, and we got the following data from it. I'm writing a script to automate reading all the translations.
```
ProgramID Translation            ShortName
--------- -----------            ---------
        1 Pots & Pans            PRG_INTENSIV
        2 Clean Machine          CAREFUL_CLEANING
        3 Economy                ECO
        5 Normal                 NORMAL
        6 Sensor Wash            AUTOMATIC_EU1_AUS_JAP
        7 Sensor Wash            AUTOMATIC_EU2
        8 Sensor Wash            AUTOMATIC_EU3
        9 EnergySaver            SOLARSPAR
       10 China&Crystal          MILD
       11 ExtraQuiet             EXTRA_QUIET
       12 SaniWash               HYGIENE
       13 QuickPowerWash         QUICK_POWER_WASH
       14 Starch & Cheese        PASTA_PAELLA
       17 Tall items             WITHOUT_BASKET
       19 Glasses - No Rinse Aid SCHOONER_WARM
       21 QuickIntenseWash       QUICK_INTENSE_WASH
       22 Economy                ECO_AUS
       23 Normal                 NORMAL_USA
       24 Rinse & Hold           RINSE_AND_HOLD
       25 Filters                GRATES_AND_FILTERS
       26 QuickIntenseWash       PL_SHORT
       27 Universal              PL_UNIVERSAL
       28 Pots & Pans            PL_INTENSE
       29 China & Crystal        PL_GLAS
       30 SaniWash               PL_HYGIENE
       31 ECO                    PL_ECO_EUR_BE_GB
       32 Plastics               PL_SYNTHETICS
       33 Rinse & Hold           PL_COLD_PRECLEANING
       34 ECO                    PL_ECO_USA_CDN
       35 ECO                    PL_ECO_AUS
       40 EcoCare                CN_ECOCARE
       41 Sensor Wash            CN_INTELLIGENT_WASH
       42 Rice Special           CN_RICE_SPECIAL
       43 Pots & Pans            CN_INTENSIVE_WASH
       44 PowerWash              POWER_WASH
```

**Comment by astrandb** [comment]
Great! I really hope this initiative will be succesful. However, I am somewhat pessimistic since we have found many small (and bigger) differences between the public API and the internal API that Miele uses for the apps.

**Comment by juliekoubova** [comment]
Yeah, it's probably not gonna match 100%, but it could fill some gaps.

https://github.com/juliekoubova/miele/tree/xamarin_extract/scripts/output

**Comment by astrandb** [comment]
This is really helpful. I did a half-hearted attempt to poke into the Android code some time ago, but I could not get any useful data.
Do you think it would be possible to extract program strings for other appliances also, washing machines, dryers, etc ?

**Comment by mundschenk-at** [comment]
Interesting that they apparently have loads of country specific programs.

**Comment by juliekoubova** [comment]
> Do you think it would be possible to extract program strings for other appliances also, washing machines, dryers, etc ?

Yup, should be pretty easy! I'll try another one.

Question is how to implement this in a scalable way. I think the best long-term solution would be to have separate keys for program names of different appliances, so we don't accidentally introduce even more conflicts (the JSON suggests something like that, generating all the names with a `dishwasher_program_` prefix). But that's obviously a breaking change for people depending on the current names.

I started working on my own integration this weekend (and then found yours and stopped, since you've fixed all the issues I have with the other integration). I was planning to have most of the smarts in the library layer (i.e. `pymiele`). That was before I fully realized how messy this stuff is :smile: But I still think it would be a good approach, maybe someone could even use it outside Home Assistant.

I'm thinking of an object model like this:

```python
class MieleValue(Generic[T]):
  raw: T | None # converted into native format
  localized: str | None # the localized value from API
  unit: str | None

class MieleDeviceType(Enum):
  GENERIC = 0
  WASHING_MACHINE = 1
  TUMBLE_DRYER = 2
  DISHWASHER = 7
  # ...

class MieleDevice:
  """
  Allows clean access to all the data provided by the API,
  normalizing temperatures, replacing -32768 with None, etc.
  """
  def key(self) -> str
  def model(self) -> str
  def type(self) -> MieleDeviceType
  def temperatures(self) -> list[MieleValue[float]]
  def is_door_open(self) -> bool
  # etc...
```

and building upon that, there would be a layer of descriptors. Those would express what is currently expressed in the entity descriptors in the integration, only moved to `pymiele` and we'd have multiple layers of them.

```python
class FridgeFreezerDescriptor(MieleDeviceDescriptor):
  def temperatures(self):
    """Described temperatures get to be enabled by default in HA""
    return [ 
      TemperatureDescriptor("Temperature"), 
      TemperatureDescriptor("Freezer temperature", icon="mdi:freezer"),
    ]

  def DishwasherDescriptor(MieleDeviceDescriptor):
    # ...

  def DishwasherG9710Descriptor(MieleDeviceDescriptor):
    def program_name(self, program_id: DishwasherProgramID):
      if program_id == 44:
        return "dishwasher_program_power_wash"
      # delegate to a more generic implementation
      return self.generic_dishwasher.program_name(program_id)
```

We would have generic descriptors for each of the device types, and we could then simply add overrides for specific models, or even more granular.

What do you think?

**Comment by mundschenk-at** [comment]
I don't know much about Python idioms, but would it be possible to make the program ID handling more generic (i.e. letting it load some JSON data from description files instead of hardcoding program IDs)? That would make adding new devices much easier. 

If you could retrieve program lists for other devices from the Android app, I'd like to make a per-device "database" via a spreadsheet to look for similarities/patterns. Right now, I've got a list compiled from various sources (other integrations, my own devices, ...) but that assumes that each device class has a non-conflicting list and currently does not identify the source for each program ID/name pair. I'll split that up into one spreadsheet for each device class, with columns by device. It can't be all random, can it?

**Comment by juliekoubova** [comment]
Extracted the laundry resource keys, not the actual values yet... Does anything there look familiar? I don't have a Miele washer 😞  https://github.com/juliekoubova/miele/blob/xamarin_extract/scripts/output/laundry-programs.txt

**Comment by juliekoubova** [comment]
> I don't know much about Python idioms, but would it be possible to make the program ID handling more generic (i.e. letting it load some JSON data from description files instead of hardcoding program IDs)? That would make adding new devices much easier.

Yup, sure, using this approach, we can have data-driven descriptors, too, if it makes sense. Depends how many conflicts there are 🤷🏻‍♀️

**Comment by mundschenk-at** [comment]
> Extracted the laundry resource keys, not the actual values yet... Does anything there look familiar? I don't have a Miele washer 😞 https://github.com/juliekoubova/miele/blob/xamarin_extract/scripts/output/laundry-programs.txt

`Dop2WmProgram` would appear to be the washing machine programs (I have lot of empty slots in my current table, but what is there appears to match what I've pulled together so far.

So we probably have:
- `Dop2WmProgram`: washing machines
- `Dop2TdProgram`: tumble dryer

Not sure about the others. The `SemiProfessional*Program` lists probably refer to their "professional" line, but are to short to be the full lists. Maybe those are a kind of diffs already?

Interestingly, my washer-dryer seems to follow the washing machine program table, i.e. those programs that I've only found on my device and that are related to the dryer function appear in the `Dop2WmProgram` table. Some programs in my Tumble Dryer column do not appear in the extracted lists at all. Unfortunately, I have not recorded their origin :(

**Comment by mundschenk-at** [comment]
PS: Have you got any idea @juliekoubova why the extracted IDs are sometimes German and sometimes English within the same group?

**Comment by juliekoubova** [comment]
> why the extracted IDs are sometimes German and sometimes English within the same group?

No idea. Maybe they originally used German, and then decided to switch to English to more easily hire devs who don’t speak German? I don’t think there’s a deeper meaning in that

**Comment by mundschenk-at** [comment]
> No idea. Maybe they originally used German, and then decided to switch to English to more easily hire devs who don’t speak German? I don’t think there’s a deeper meaning in that

Ah, OK. I was wondering whether they were an artifact of the extraction process.

**Comment by juliekoubova** [comment]
Nah, it’s what the strings are referred to in code. I’ll get the actual localized values tomorrow, same as for the dishwasher

**Comment by astrandb** [comment]
@juliekoubova 
> I started working on my own integration this weekend (and then found yours and stopped, since you've fixed all the issues I have with the other integration). I was planning to have most of the smarts in the library layer (i.e. `pymiele`). That was before I fully realized how messy this stuff is 😄 But I still think it would be a good approach, maybe someone could even use it outside Home Assistant.
> 
> I'm thinking of an object model like this:

I started to develop this integration for the same reasons as you stated above. My philosophy has been to try to keep it simple, to avoid complex interpretations of API data and to follow developer guidelines from the HA core team.

One sentence I chose to follow was [API libraries should try to do as little as possible](https://developers.home-assistant.io/docs/api_lib_data_models). I have experience from another integration for HA where we put some effort into data modelling and interpretation in the API lib. It works fine but it has required a new release of the library everytime a little change in the data model was made (which could easily been handled in the main integration).

So it has not been a priority to refactor the library or to develop and refine object models.

The main challenge has been to map the functions that Miele exposes through the 3rd party API to the entities and interface elements in Home Assistant - without having access to the different appliances. I own a connected  freezer and a refridgerator while the rest of my appliances are of an older generation - and they never break...

However, it is important to try to display correct programs, program phases, status messages and device types and to have an underlying structure that is easy to maintain when new appliance types or programs pop up. It would have been easier if Miele kept the API updated and used unique numeric codes and always included the clear text names, but that is not how they manage the API.

**Comment by the-ress** [comment]
@astrandb 
> I did a half-hearted attempt to poke into the Android code some time ago, but I could not get any useful data.

The interesting stuff was hiding in the `assemblies.blob` file. Here's how to unpack it: https://www.thecobraden.com/posts/unpacking_xamarin_assembly_stores/

(Then you can look inside the assemblies with something like [ILSpy](https://github.com/icsharpcode/ILSpy).)

**Comment by juliekoubova** [comment]
Hey, got back to this and added all the laundry program name translations. I also changed the output format of the scripts: there is a single `strings_<culture>.json` file with all the strings, and individual JSON files mapping the program numbers into keys to those strings. I hope this format will make it easier to use in the integration.

Washers and dryers are separated; there are three "generations" of each. `dop1` (also called legacy in the DLLs), `dop2`, and `semipro`. We'll have to figure out how to detect the device type, there are conflicts between the numeric values.

I'll probably try the ovens next.

https://github.com/juliekoubova/miele/tree/xamarin_extract/scripts/output

**Comment by astrandb** [comment]
Magnificent piece of reverse engineering. I agree that it can be a challenge to find out what "generation" a device belongs to.

BTW: Have you got an oven? In that case I am interested in a diagnistic dump. There is a new feature regarding food core temperature in API v 1.0.6 that was released last week. It is not documented and Miele doesn't answer any questions, at least not yet.

**Comment by juliekoubova** [comment]
Nice, good to hear they are adding features. I ran a program that uses the food core temperature sensor, and it seems to be correctly reported:
```
        "state|targetTemperature|0|value_raw": 8000,
        "state|targetTemperature|0|value_localized": 80.0,
        "state|targetTemperature|0|unit": "Celsius",
        "state|targetTemperature|1|value_raw": -32768,
        "state|targetTemperature|1|value_localized": null,
        "state|targetTemperature|1|unit": "Celsius",
        "state|targetTemperature|2|value_raw": -32768,
        "state|targetTemperature|2|value_localized": null,
        "state|targetTemperature|2|unit": "Celsius",
        "state|coreTargetTemperature|0|value_raw": 5600,
        "state|coreTargetTemperature|0|value_localized": 56.0,
        "state|coreTargetTemperature|0|unit": "Celsius",
        "state|temperature|0|value_raw": 7018,
        "state|temperature|0|value_localized": 70.18,
        "state|temperature|0|unit": "Celsius",
        "state|temperature|1|value_raw": -32768,
        "state|temperature|1|value_localized": null,
        "state|temperature|1|unit": "Celsius",
        "state|temperature|2|value_raw": -32768,
        "state|temperature|2|value_localized": null,
        "state|temperature|2|unit": "Celsius",
        "state|coreTemperature|0|value_raw": 4425,
        "state|coreTemperature|0|value_localized": 44.25,
        "state|coreTemperature|0|unit": "Celsius",
```

[config_entry-miele-7e2a4791b88e377cce5e6e5123804988.json (2).txt](https://github.com/astrandb/miele/files/10231995/config_entry-miele-7e2a4791b88e377cce5e6e5123804988.json.2.txt)
