### ISSUE TITLE
Water and energy consumption remain zero

### ISSUE THREAD

**Issue by geert36** [astrandb/miele#162]
### The problem

The values of Energy and Water Consumption remain zero:
![image](https://user-images.githubusercontent.com/77209691/205457295-f991301a-a14e-486e-808b-2659d5b55f5d.png)
[miele-56710ae87bb296fc0fda65a029bbdffe-Washing machine-644bf2d5d5bd2917c74d84766bea2ae5.json (1).txt](https://github.com/astrandb/miele/files/10147166/miele-56710ae87bb296fc0fda65a029bbdffe-Washing.machine-644bf2d5d5bd2917c74d84766bea2ae5.json.1.txt)

### Version of miele integration having the issue?

miele-0.1.0

### Version of Home Assistant Core having the issue?

core-2022.11.5

### Additional information

Miele Washing Machine Type: WSF363

**Comment by astrandb** [comment]
Zero.zero is exactly what the Miele API reports according to the attached log file.

**Comment by geert36** [comment]
So my washing machine does not report these values?

**Comment by mundschenk-at** [comment]
The public Miele API does not. The washing machine probably does.

**Comment by rudizl** [comment]
Not sure, but this model does not show consumption. Do you see that data in official android app?

**Comment by geert36** [comment]
Hmm no, I cannot find it. Under which tab should it be available?

**Comment by rudizl** [comment]
You have to start a program first. Mine is WCR860.
![image](https://user-images.githubusercontent.com/5582186/205485990-4ec5dd9d-c675-4d8a-8fc4-e9d9362a8f93.png)

![image](https://user-images.githubusercontent.com/5582186/205486073-6205a465-be4d-4613-8e76-5e4cfd7f4014.png)

**Comment by geert36** [comment]
I see only max weight under information. So I think my machine isn't reporting these values.
