### ISSUE TITLE
Use correct country code when authenticating

### ISSUE THREAD

**Issue by astrandb** [astrandb/miele#167]
### Feature request

Currently sv_SE is used for all logins to OAuth2 authentication server. It seems to work, but according to the spec the country code should be pointing to the Miele subsidiary where the account is registered.

Country codes are saved in `devcap.py` for the time being.

### What version of the integration are you using?

1.0.0

### Additional information

Read more here: https://www.miele.com/developer/authorization.html

**Comment by joel-bourquard** [comment]
Ah, could this be the reason why I'm getting this message every few days? (I'm in Switzerland):

Miele re-authentication
Miele integration for account miele needs to be re-authenticated. Please go to the integrations page to re-configure it.
