### ISSUE TITLE
 Consumption sensors

### ISSUE THREAD

**Issue by tomasb82** [astrandb/miele#196]
### Feature request

Is it possible to add energy and water consumption sensors for applaences.

### What version of the integration are you using?

0.1.4

**Comment by aturri** [comment]
Hi,
There are already the consumption sensors for washers, dryers, washer-dryers and dishwashers. Sensors are disabled by default, so you have to navigate to your device page and enable sensors.

**Comment by tomasb82** [comment]
Tx, my bad :)

**Comment by IngmarG** [comment]
I have previously already enabled those (dishwasher and dryer), but I also have a Miele@Home fridge (K 7343 D), which doesn't have energy consumption as an entity.
Maybe there is no energy consumption sensor, but if there is, it would be very nice to have that also in one of the next Miele integration versions.
Great work, and thx for your efforts.

**Comment by astrandb** [comment]
Consumption data is available on some later models of washing machines, dryers, washer/dryers and dish-washers. No other appliances report consumption data.
