### ISSUE TITLE
Spinning circle when trying to configure integration

### ISSUE THREAD

**Issue by astrandb** [astrandb/miele#198]
I've just installed this integration and just get a spinning circle when trying to configure it - Im accessing my home assistant via Nabu Casa (https://xxxxxxxxxx.ui.nabu.casa/) which I guess is a reverse proxy of sorts.

I'm not currently on my local LAN so can test further later on, but I suspect this might be the same issue?

_Originally posted by @bradleykite in https://github.com/astrandb/miele/issues/197#issuecomment-1377048317_

**Comment by bradleykite** [comment]
After trying to troubleshoot for 2 hours, decided to "turn it off and turn it on again" - even though I'd done this already as part of the initial install.

Suddenly it starts working as expected with no explanation.

Sorry if I was too quick to open an issue for it, it seems like maybe something didnt start correctly the first time round?

**Comment by astrandb** [comment]
NP, I was just writing a response with some instructions. The first item was the one you just tried.
It looked like the error occurred very early during setup since there were no error traces from the actual integration code.
