### ISSUE TITLE
Miele services generate "400 Bad Request" response

### ISSUE THREAD

**Issue by MattieGit** [astrandb/miele#199]
### The problem

I've successfully setup the integration. Miele devices and entities are available. Some of the controls work via Home Assistant (e.g. turning the light of the coffee machine on), other actions are not working.
Example: turning the coffee machine on or off (via Devices in HA) does not work. Doing the same with one of the available Miele services in HA Developer Tools triggers a 400 Bad Request.

I can successfully switch the coffee machine on or off via the Miele mobile app, so it appears the Miele API is working.
Same goes for the oven, so it's not isolated to just one device.

The logs don't show any specific details.

### Version of miele integration having the issue?

miele-0.1.4

### Version of Home Assistant Core having the issue?

core-2023.1.2

### Anything in the logs that might be useful for us?

```txt
This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/miele/switch.py:229
Integration: Miele (documentation, issues)
First occurred: 20:36:28 (1 occurrences)
Last logged: 20:36:28

Error executing service: <ServiceCall switch.turn_on (c:01GPKQQB7FJ3TXQ4F4PWKXY6NA): entity_id=['switch.coffee_machine_power_on']>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pymiele/pymiele.py", line 90, in send_action
    res = await self.request(
  File "/usr/local/lib/python3.10/site-packages/pymiele/pymiele.py", line 58, in request
    return await self.websession.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1773, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/miele/switch.py", line 229, in async_turn_on
    await self._api.send_action(self._ent, self.entity_description.on_data)
  File "/usr/local/lib/python3.10/site-packages/pymiele/pymiele.py", line 89, in send_action
    async with async_timeout.timeout(10):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
```

**Comment by astrandb** [comment]
> ```
>   File "/config/custom_components/miele/switch.py", line 229, in async_turn_on
>     await self._api.send_action(self._ent, self.entity_description.on_data)
>   File "/usr/local/lib/python3.10/site-packages/pymiele/pymiele.py", line 89, in send_action
>     async with async_timeout.timeout(10):
>   File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
>     self._do_exit(exc_type)
>   File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
>     raise asyncio.TimeoutError
> asyncio.exceptions.TimeoutError
> ```

This error signals that there was a timeout when accessing the Miele servers. As a general comment: The public 3:rd API that this integration uses is something entirely different and more restricted than the API Miele is using for their internal use in the apps.
I have no coffee system so I forward the question to @aturri - Have you seen this while working with the integration for the coffee systems?

**Comment by aturri** [comment]
For me it is working properly. The only way I’m able to get a 400 is when explicitly invoking the service switch.turn_off and the coffee machine is already off. No timeout in this case.

If I understood correctly, however this issue is related also to the oven / other appliances for @MattieGit 
Can you provide device diagnostic data (you can download in devices page)?

**Comment by MattieGit** [comment]
@astrandb Thanks for the update and understood regarding the difference between the public API and Miele-internal API.

@aturri Correct, it's not just the coffee machine, but also the oven. I know there will be a time-out when switch off a device that is already off, but it's also happening when switching a powered-off device to on.
I have attached the device diagnostic data for the coffee machine and the oven
[miele-f79543d6e3b50547b352f713ef9aa784-Coffee machine-ba622dd3b6e25e3a20229d3e1e94d059.json.txt](https://github.com/astrandb/miele/files/10411842/miele-f79543d6e3b50547b352f713ef9aa784-Coffee.machine-ba622dd3b6e25e3a20229d3e1e94d059.json.txt)
[miele-f79543d6e3b50547b352f713ef9aa784-Oven-c830e178d371bcf6eeafdf44a74e10df.json.txt](https://github.com/astrandb/miele/files/10411843/miele-f79543d6e3b50547b352f713ef9aa784-Oven-c830e178d371bcf6eeafdf44a74e10df.json.txt)
. Happy to provide diagnostic data for other devices as well.

**Comment by astrandb** [comment]
```
      "state|remoteEnable|fullRemoteControl": true,
      "state|remoteEnable|smartGrid": false,
      "state|remoteEnable|mobileStart": false,
```
The only suspicious thing is that I can see is `Enable mobileStart: false`. Is there a setting for that in your devices?

**Comment by aturri** [comment]
No, `mobileStart` enables setting a program (= selecting a drink), it's not related to power on/off.

I see that you have `protocolVersion` = 2 (current is 4), so there can be some differences (also, your hardware is named "XKM3000Z", while latest ones are EK037 or EK057).

Can you try using the Swagger provided by Miele? https://www.miele.com/developer/swagger-ui/index.html#/Actions/putActionsById
You have to authorize it and then you can try the PUT on actions endpoint (in examples there is the one for powerOn/powerOff).
Maybe it's a problem of your hardware that is taking longer to receive action and it causes the timeout.

**Comment by mundschenk-at** [comment]
XKM3000Z is a Zigbee-based retrofit-module using a separate gateway for cloud connectivity, if I'm not mistaken.

**Comment by MattieGit** [comment]
Very good point. These devices are indeed using the older Zigbee based modules which communicate with a dedicated Miele hardware gateway. I'll test Swagger tomorrow and based on the outcome I might have to update the modules.

**Comment by MattieGit** [comment]
I just tested using Swagger. Powering on the coffee machine results in a 500 server error. I don't have a spare wifi Miele module to test this instead of the current Zigbee module, but will try shortly and get back with an update. Thanks for the help so far!

```
{
  "code": 500,
  "message": "A technical error occured. Please try again later. (Error-ID: 949c7f5f63da5c84)"
}
```
