### ISSUE TITLE
Friendly Names

### ISSUE THREAD

**Issue by beasthouse-au** [astrandb/miele#200]
### Feature request

Would like to see friendly names for states displayed

### What version of the integration are you using?

0.1.4

### Anything in the logs that might be useful for us?

```txt
No
```

### Additional information

Snippets of what currently displays. 

![image](https://user-images.githubusercontent.com/78465928/212224925-465b75ae-05b5-439c-892e-08bfaf52331a.png)

**Comment by beasthouse-au** [comment]
- What version of HA? 
        Home Assistant 2023.1.1
        Supervisor 2022.12.1
        Operating System 9.4
        Frontend 20230104.0 - latest

- Does it look right on the device page?
        Looks good here
        ![image](https://user-images.githubusercontent.com/78465928/212281388-dd0c9237-e428-4315-b18d-8eb4b6d26f3c.png)

- What card are you using to display the entities?
        custom:button-card

**Comment by astrandb** [comment]
OK, the problem is that the custom card does not pick up the translated strings properly.

**Comment by beasthouse-au** [comment]
Thanks a lot, must be it!

**Comment by astrandb** [comment]
Similar issue is already reported.
https://github.com/custom-cards/button-card/issues/646
