### ISSUE TITLE
New model for translations in Home Assistant

### ISSUE THREAD

**Issue by astrandb** [astrandb/miele#201]
### Feature request

Translation of status for text sensors is updated in Home Assistant. The short version is that the content of `sensor.xx.json` files is moved into `xx.json` files.
Read more here: [developer docs](https://developers.home-assistant.io/docs/internationalization/core#entities)

This is not a breaking change, but I guess that the old model with `device_class = miele__someclass` will be deprecated. Hopefully this new model will support localization of entity names in the future. I have read some rumors....

### What version of the integration are you using?

2023.1 going forward

**Comment by Labu7** [comment]
HI, I have made a translation on french of the language, not familiar with Git so I drop the file with this message.
[fr.zip](https://github.com/astrandb/miele/files/10516810/fr.zip)

**Comment by astrandb** [comment]
OK, thanks. I will take care of the translation file.
