### ISSUE TITLE
Version 1.5. gives errors at startup, senors and switches are in unreachable/unknown status

### ISSUE THREAD

**Issue by odelma** [astrandb/miele#212]
### The problem

Upgrading from 0.1.4. to 0.1.5.  is currently not working for me. In notifications it says “cannot create/setup miele.sensors platform” (or close to this - unfortunately I already cleared it and logs are empty) and all existing miele sensors and switches are in unreachable status. Downgrading to 0.1.4. restored normal operation.

### Version of miele integration having the issue?

0.1.5.

### Version of Home Assistant Core having the issue?

2022.11.4.

### Anything in the logs that might be useful for us?

```txt
Unfortunately nothing. I guess I would need to enable debugging?
```

**Comment by astrandb** [comment]
Please upgrade your Home Assistant to 2023.1.0 or later. I am sorry that I forgot to set the requirement in hacs.json. It should have held back the upgrade of the integration.

**Comment by odelma** [comment]
Ok, thanks - should've tried it before opening the issue 🙂 Will reopen this in case there are problems once I get around to update HA. Thanks for your work with the integration 🙏
