### ISSUE TITLE
Account linking failed

### ISSUE THREAD

**Issue by riccmike** [astrandb/miele#220]
### The problem

after entering Secret_id and Miele ID, I am redirected to the Miele login page. BUT after entering the email and password used in the smartphone app, the non-pairing error message appears. If I run everything again, the procedure no longer asks me for SecretID and MieleID, why and where does HA store these two info?
Thanks in advance for the help.

### Version of miele integration having the issue?

1.4, 1.5, 1.6

### Version of Home Assistant Core having the issue?

core-2023.1.7

**Comment by lechiel** [comment]
I have the same problem. I think we can use the same credentials as in the App right?

**Comment by astrandb** [comment]
Go to Settings->Integrations -> three-dot-menu -> Application Credentials to manage stored credentials.

There is a known problem that the Miele API does not accept special characters in passwords - even though it is OK with the Miele app.

You can verify your credentials at https://www.miele.com/developer/swagger-ui/ -> [Authorize button]. If you are allowed access there, the integration will usually work also.

**Comment by lechiel** [comment]
I dont have any special charcacters (only letters ans numbers). I have te same problem with the Authorize button. 

Is there are different account i need to use for the login, or is it the same as the mobile app

**Comment by astrandb** [comment]
It should be same username and password as in the app.
Make sure that the client_id and client_secret are entered correctly. No whitespace before or after.

**Comment by lechiel** [comment]
Oke, It's working. I reactivate the code and copied it again. Now it's working strange.... There is no difference in what I copied. Maby you need to copy it to a notepad first to remove some hidden characters.

Thx for the help
