### ISSUE TITLE
integrations and platforms could not be set up:

### ISSUE THREAD

**Issue by neildsb** [astrandb/miele#227]
### The problem

just updated to 0.1.7

Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

Logger: homeassistant.util.package
Source: util/package.py:100
First occurred: 3:05:35 pm (3 occurrences)
Last logged: 3:05:40 pm

Unable to install package pymiele==0.1.7: ERROR: Could not find a version that satisfies the requirement pymiele==0.1.7 (from versions: 0.1.0, 0.1.2, 0.1.3, 0.1.4rc3, 0.1.4rc4, 0.1.4, 0.1.5b1, 0.1.6) ERROR: No matching distribution found for pymiele==0.1.7 [notice] A new release of pip available: 22.3 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

Logger: homeassistant.setup
Source: setup.py:205
First occurred: 3:05:40 pm (1 occurrences)
Last logged: 3:05:40 pm

Setup failed for custom integration miele: Requirements for miele not found: ['pymiele==0.1.7'].

### Version of miele integration having the issue?

0.1.7

### Version of Home Assistant Core having the issue?

2023.2.5

### Additional information

0.1.6 all good

**Comment by rudizl** [comment]
Same here

**Comment by woempiej** [comment]
Same here;

![afbeelding](https://user-images.githubusercontent.com/62903344/221901115-e98bf107-ff4a-4438-a100-caf53e1083ea.png)

**Comment by astrandb** [comment]
Fixed in v0.1.8

**Comment by neildsb** [comment]
looks good, thanks
