### ISSUE TITLE
Warning for sensor started_at

### ISSUE THREAD

**Issue by Gloomyeye** [astrandb/miele#229]
### The problem

Hello,
first, thanks for the integration!
I get the following warning with the current beta version of Home Assistant 2023.3 that the sensor "started_at" has not a correct value (hh:mm for a numeric value). Maybe the value needs to be changed to a timestamp with the current device class.
I think that the same warning will occur also for "finish_at" and "start_at".

### Version of miele integration having the issue?

miele-0.1.8

### Version of Home Assistant Core having the issue?

core-2023.3.0b5

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:592
Integration: Sensor (documentation, issues)
First occurred: 07:53:40 (1 occurrences)
Last logged: 07:53:40

Sensor sensor.hwr_miele_dryer_started_at has device class None, state class None and unit thus indicating it has a numeric value; however, it has the non-numeric value: 05:57 (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
```

**Comment by astrandb** [comment]
Thank you for reporting this issue. 
This is a warning message and should not cause any immediate problems.
The fix requires change of device_class to `SensorDeviceClass.TIMESTAMP` and also change of the internal data type of the time stamp.

**Comment by Gloomyeye** [comment]
Thank you very much for your correction effort. You are right, this doesn’t need to be corrected immediately.

**Comment by astrandb** [comment]
@mundschenk-at There is a risk of opening a can of worms when fixing this issue. If you remember we had problems with the absolute time sensors that would spam the logbook when the values were toggling one minute back and forth. It was managed by assigning an empty string as unit for the sensor and that made HA treat the sensor as numeric and thus not create any logbook entries.
It is now no longer allowed to assign a string as unit to a sensor without a device class. It is also forbidden to assign non-numeric values (e.g 22:05) to a numeric sensor. The only way I can see to avoid the warning message is to assign a device\_class of timestamp or removing the measurement unit. In either way the changed sensor values will le logged in the logbook. 
If we use a timestamp type for the absolute time it will be displayed as an approximate relative time, e.g. "In one hour" in the entity card, and that is not precise enough from my perspective.
By the way, the same logging happens with similar absolute time sensors in all official integrations that I have looked into.

All suggestions are welcome.

**Comment by mundschenk-at** [comment]
Yes I do remember. Could we simply ignore 1 minute changes to those sensors (i.e. dejitter the API values)? If there is no other way, logbook entries can be suppressed manually for those entities, but I still think dejittering them is better than providing the raw API results in this case.

As for the device class, I think `timestamp` would be the correct choice. The default relative display can be worked around with a template (and eventually a UI setting similar to the new precision selection in `2023.3.0`.

**Comment by astrandb** [comment]
I have done some experimenting and it seems to be difficult to keep all stakeholders happy.

- The way to get rid of the log warning is to remove `native_unit_of_measurement` from the applicable sensors.
- There is no real point to change the device class to `TIMESTAMP` until there is core and frontend support for custom formatting.
- If the user is annoyed by too frequent entries in the logbook they can exclude the sensor by appropriate settings in configuration.yaml

Non-numeric sensors that change value frequently all show similar behaviour. A common example is wind direction sensor that toggle value between North and North-North-East each and every reading. As there is no built-in support to programatically exclude sensors from the logbook we have to rely on manual exclusion in configuration.yaml.
