### ISSUE TITLE
Temp and target temp sensors are not represented properly

### ISSUE THREAD

**Issue by astrandb** [astrandb/miele#23]
### The problem

Temperature sensors should support `unknown` value. Same for target temperature. Certain appliances display target temperature only when they are active.

### Version of miele integration having the issue?

miele-0.0.9

### Version of Home Assistant Core having the issue?

core-2022.2

**Comment by mundschenk-at** [comment]
I don't think #26 closes this issue.

**Comment by astrandb** [comment]
Well, my fingers slipped earlier today and one commit went directly into the main branch. https://github.com/astrandb/miele/commit/52a24b133a88b413c9cee9869b3f9926be2640a6
Or did you have anything else in mind?

**Comment by mundschenk-at** [comment]
Ah, no, that was it!
