### ISSUE TITLE
Enable translated entity names

### ISSUE THREAD

**Issue by astrandb** [astrandb/miele#244]
### Feature request

Home Assistant suppports translation of entity names and state attributes from 2023.4
Enable this feature for Miele integration.

### What version of the integration are you using?

x

**Comment by TAOGde** [comment]
Dunno is this the right place for but in German HA the entitie entrys in german, with `{{ states('sensor.washer_dryer_programmabschnitt') }}` i got not the localized attributes it is all english.
[config_entry-miele-c9af1a57711e062bc38e1e74de6ed485.json](https://github.com/astrandb/miele/files/14623404/config_entry-miele-c9af1a57711e062bc38e1e74de6ed485.json)

**Comment by astrandb** [comment]
I guess the {{ }} indicates that you are using a template to show the entity state. The translation of the states happens only in frontend in HA so I think you will get the english states in your templates.

**Comment by TAOGde** [comment]
> I guess the {{ }} indicates that you are using a template to show the entity state. The translation of the states happens only in frontend in HA so I think you will get the english states in your templates.

it is an markdown card.
