### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by SheriffOfNotts** [astrandb/miele#248]
### The problem

Hello, I tried the other Miele integration before finding this one. I uninstalled the old add-in and deleted the miele: section from my configuration.yaml file.

I have installed the integration and when I try to install it via integrations I get the enclosed? haintegration refers to the old version configured on the Miele developer’s website. Please can you let me know how to change this or reset the configuration?

<img width="343" alt="image" src="https://user-images.githubusercontent.com/16319499/230160312-421dfc25-20c6-441d-a657-23cbb8858c2c.png">

### Version of miele integration having the issue?

Unable to load the configuration panel

### Version of Home Assistant Core having the issue?

Home Assistant 2023.3.6

### Anything in the logs that might be useful for us?

```txt
None
```

**Comment by astrandb** [comment]
Look here https://github.com/astrandb/miele/discussions/247

**Comment by SheriffOfNotts** [comment]
Thanks for the quick response - never knew that menu was there!

I've deleted the Miele references and now get the dialog box. I have re-registered with Miele, but I keep getting "authentication failed" messages? Any idea?

**Comment by astrandb** [comment]
A few other people have also had these problems. You can look here https://github.com/astrandb/miele/discussions/112 for ideas

**Comment by SheriffOfNotts** [comment]
Thank you. All working - the only change I made was to change my Miele password to one without special characters
