### ISSUE TITLE
Multiple HA's access to one "Miele developer" account

### ISSUE THREAD

**Issue by peterczarlarsen-ha** [astrandb/miele#255]
### The problem

HI

I have two locations, and two Home Assistant setups. I have one Miele account, with in total two dryers, and one washer.

I have tried to include the same oauth and key on both home assistant, and then deactivate the hardware that I do not need on the location. 

for some reason, it seems to deactivate the "other" home assistant Miele integration.

I have also tried to make a "new" client/key set, result was the same

Am I hitting a limitation in the Miele developer access, or?

The easy solution would be to split it up, but then I will need to swap between accounts on Miele's app...

### Version of miele integration having the issue?

0.1.9

### Version of Home Assistant Core having the issue?

2023.3.6

**Comment by astrandb** [comment]
I have not run into this problem even though I have my production instance running continously and at least one development system with same credentials running for anything between minutes and many days. I have never been disconnected unexpectedly from the API.
It would be helpful if you can get a full debug log from the integration, it might reveal error codes from Miele servers when disconnect happens.
I suggest that you ask Miele developer support if there are any constraints regarding number of simulataneous user on an account.

**Comment by peterczarlarsen-ha** [comment]
thanks for the feedback, I'll give it a few more shots and if it fails I'll  try to see if I can get anything in the debug log of common interest :)
