### ISSUE TITLE
Start button no longer works

### ISSUE THREAD

**Issue by gigatexel** [astrandb/miele#257]
### The problem

Issue seems introduced by latest update.
Pressing the "Start" button on the washing machine, throws an error:

### Version of miele integration having the issue?

0.1.12

### Version of Home Assistant Core having the issue?

Home Assistant 2023.4.2

### Additional information

![image](https://user-images.githubusercontent.com/65073191/231119763-3ddde4e3-6e8e-453b-8275-84630dc4f781.png)

**Comment by astrandb** [comment]
Thank you for reporting. Fixed in PR #258
I am waiting for a few other fixes and plan to release later today or tomorrow. If you are in a hurry you can reinstall version "main" via HACS as soon as this PR is merged.
