### ISSUE TITLE
Prompt for Auth not loading

### ISSUE THREAD

**Issue by NickWhitNTES** [astrandb/miele#266]
### The problem

I have added the integration, rebooted, and added the integration.  The initial prompt that it is setting up loads for some time, then no prompt to authenticate comes up.

Now, if I try to add, the initial prompt flashes for just a small second, then nothing.

Any ideas?

### Version of miele integration having the issue?

latest

### Version of Home Assistant Core having the issue?

latest

**Comment by NickWhitNTES** [comment]
My issue seems similar to this:
https://github.com/astrandb/miele/issues/197

I am using Letsencypt.  But it also does not need to work locally

**Comment by Subbilein** [comment]
Same Issue here. 
latest version and latest HA OS.

**Comment by NickWhitNTES** [comment]
So, I managed to get the prompt to load up by manually adding to the configuration the https external and internal URL. However, it still will not authenticate with the keys provided by Miele.

**Comment by Subbilein** [comment]
Now it works again in my case.
