### ISSUE TITLE
Dishwasher "Smartstart" 

### ISSUE THREAD

**Issue by VoetenK** [astrandb/miele#268]
### The problem

To start the dishwasher with an automation, I have to take the following steps on the dishwasher or in the Miele app:
- Switch on the device
- Select the programme
- Set the timer to smartstart. (end xx:xx)
- OK

If I want to use the Miele app, I can press the play button and the dishwasher will start.

If I want to do it with Home Assistant, I have to do it via Entity ID button.dishwasher_start.
The problem is that the dishwasher does not start but switches to starting now, which is not the intention. Entity ID button.dishwasher_start is then no longer available.
Then if I don't turn off the dishwasher but reset the timer to smartstart and then use Entity ID button.dishwasher_start, the dishwasher will start.

What can I do to fix this problem?

### Version of miele integration having the issue?

G7665 door Miele Firmware: 08.20 Hardware: EK057

### Version of Home Assistant Core having the issue?

Home Assistant Core Geïnstalleerde versie 2023.4.6

**Comment by astrandb** [comment]
Stale issue - closing
