### ISSUE TITLE
Integration broken

### ISSUE THREAD

**Issue by Torsten07** [astrandb/miele#271]
### The problem

Since HA version Home Assistant 2023.5.x my Miele Integration is broken and tells only "Error".

### Version of miele integration having the issue?

0.9.3

### Version of Home Assistant Core having the issue?

 2023.5.1

**Comment by astrandb** [comment]
Version 0.9.3 indicates that you are using another integration than this one. Probably https://github.com/HomeAssistant-Mods/home-assistant-miele 
You are of course welcome to change to this one. It works fine with recent versions of HA and it has quite a few more features.

**Comment by DerDreschner** [comment]
Are you sure it still works with HA 2023.5? I upgraded to 2023.5.2 and the Miele integration (current version) doesn't load anymore. I had to disable it do get HA to startup in a reasonable time.

**Comment by mundschenk-at** [comment]
What is your "current version", @DerDreschner?

**Comment by DerDreschner** [comment]
@astrandb / @mundschenk-at : It's version 0.1.13. But I wanted to debug the issue further, but as soon as I set the logging level to debug and restarted - everything works now. Don't know what was wrong, but looks like it has nothing to do with the HA 2023.5 update and the miele integration itself. :) So, sorry for any inconvenience!

**Comment by kurtSejr** [comment]
My Miele integration is also broken, HA version is 5.2 and Miele version is 0.1.13 (latest). 
It has not worked since I updated HA from 51. to 5.2. Lookin forward to have a working integration again :-)

**Comment by astrandb** [comment]
@kurtSejr We need more information to be able to assist you. Please create a new issue and describe what is happening. Any lines in the log with miele or pymiele? Please also enable debug log either in the integration card or in configuration.yaml and restart HA.
There are almost 2000 installations that don't have any problems with this latest release of the integration so we need your help with troubleshooting.
