### ISSUE TITLE
After updating to HA 2023.5.2, Miele integration stop working

### ISSUE THREAD

**Issue by kurtSejr** [astrandb/miele#272]
### The problem

Miele integration does not start. I'm also using the Miele APP on my mobile, works as normal - e.g. have not changes password. I have been using HA for 2+ years, including HACS.

Reboot does not help.

Versions:
Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Brugerflade 20230503.3 - latest

### Version of miele integration having the issue?

0.1.13

### Version of Home Assistant Core having the issue?

2023.5.2

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.setup
Source: custom_components/miele/__init__.py:127
Integration: miele (documentation, issues)
First occurred: 8. maj 2023 kl. 17.02.13 (1 occurrences)
Last logged: 8. maj 2023 kl. 17.02.13

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 257, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 127, in async_setup
    cache = config[DOMAIN].get(
KeyError: 'miele'
```

**Comment by astrandb** [comment]
There must be some mixup of two different integrations for Miele
The error message in the log emanates from https://github.com/HomeAssistant-Mods/ which is something entirely different than the integration in this repository

```
 File "/config/custom_components/miele/__init__.py", line 127, in async_setup
    cache = config[DOMAIN].get(
```

**Comment by kurtSejr** [comment]
OK, how do I best continue without reinstall HACS Miele integration?

**Comment by kurtSejr** [comment]
Alles klar!
