### ISSUE TITLE
Ventilator is "off" even it is still on

### ISSUE THREAD

**Issue by misery** [astrandb/miele#273]
### The problem

Home assistant says that the ventilator is OFF even it is still running. If I start my hob and enable the ventilator it is recognized as ON. But if I turn off the plate and let the ventilator still be on the whole hob will be recognized as OFF and the ventilator is marked as OFF.

### Version of miele integration having the issue?

0.1.13

### Version of Home Assistant Core having the issue?

2023.5.3

**Comment by astrandb** [comment]
This seems to be a problem in the Miele API. In the diagnostic dump you sent there is a line
```json
"state|ventilationStep|value_raw": null,
```
The null value received from Miele indicates that the fan is off. You can experiment with different operation modes and 
see what happens. I have no such appliance myself so I cannot do any troubleshooting of the API in this context.

**Comment by astrandb** [comment]
Stale issue - closing
