### ISSUE TITLE
Miele Integration not loading

### ISSUE THREAD

**Issue by yvansandoz** [astrandb/miele#276]
### The problem

I am unable to find a similar error report and I am unable to fix it on my own (see log below).
I did install the integration using HACS.
Error message in the integration: Not loaded

### Version of miele integration having the issue?

0.1.13

### Version of Home Assistant Core having the issue?

2023.5.4

### Anything in the logs that might be useful for us?

```txt
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/miele/__init__.py:401 
Integration: miele (documentation, issues) 
First occurred: 13:02:19 (1 occurrences) 
Last logged: 13:02:19

Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 257, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 401, in async_setup
    cache = config[DOMAIN].get(
KeyError: 'miele'
```

**Comment by astrandb** [comment]
You are using https://github.com/HomeAssistant-Mods/home-assistant-miele . Not this integration.
