### ISSUE TITLE
New program and device IDs

### ISSUE THREAD

**Issue by principis** [astrandb/miele#278]
### Feature request

Hi! I managed to find a bunch of ID's. Most of them don't seem useful, but at least `GLOBAL_EnumPrgId` seems to fill the gaps for my oven.

I'm not sure how I would integrate the IDs into the repo. We can try to test which groups of IDs are correct and implemented those. Or it can be used as a reference on the wiki for people who are missing an ID.

These are the IDs: [ids.txt](https://github.com/astrandb/miele/files/11678926/ids.txt)

### What version of the integration are you using?

0.1.13

**Comment by astrandb** [comment]
Thank you, this can definitely be useful as a reference when mappings are missing. I found a few device id:s for the semi-professional appliances. They are not officially supported by the API but nevertheless produce data when added to the user’s account.
Please describe what you miss with your oven and I can try to add it. Or feel free to make a PR.

**Comment by principis** [comment]
I can add them! :slightly_smiling_face:. For my oven it was `PHASE_OVEN_ENERGY_SAVE = 3084`, but my microwave oven combo is missing everything. They could be mapped onto oven, or would it be a better idea to create a new constant altogether?

I also found ID's for washing machines, but they sadly don't match by a factor 10 (and maybe some modifier?). I couldn't find any code on how they are mapped. Maybe they can be useful in another way: 
[laundry_care_ids.txt](https://github.com/astrandb/miele/files/11679305/laundry_care_ids.txt)

**Comment by aturri** [comment]
Hi, this is really interesting!
Thanks!
May I ask where did you find these values? 😄

**Comment by principis** [comment]
> Hi, this is really interesting! Thanks! May I ask where did you find these values? smile

Hi, from the Miele app!

I decoded the app with `apktool d`, then used [this](https://github.com/jakev/pyxamstore) tool to unpack the xamarin blob. Finally I used an ILSpy fronted for linux to decompile the dll's. That last part was the hard part. I probably should've done that on Windows with a better frontend.

**Comment by aturri** [comment]
Wow! Thanks a lot :D

**Comment by astrandb** [comment]
Stale issue - closing
