### ISSUE TITLE
Miele integration not loaded: "No module named 'flatdict'

### ISSUE THREAD

**Issue by bertmelis** [astrandb/miele#279]
### The problem

```
Logger: homeassistant.setup
Source: setup.py:215
First occurred: 9:22:03 AM (1 occurrences)
Last logged: 9:22:03 AM

Setup failed for custom integration miele: Unable to import component: No module named 'flatdict'
```

I just upgraded my HASS Docker to 

```
Home Assistant 2023.6.0
Frontend 20230607.0 - latest
```

### Version of miele integration having the issue?

v0.1.13

### Version of Home Assistant Core having the issue?

Home Assistant 2023.6.0

**Comment by astrandb** [comment]
Well, it works with HAOS container and dev container. HA is supposed to install dependencies according to requirements stated in manifest.json. I dont understand why this does not work in your setup. Please try to restart your machine and see if that helps.
