### ISSUE TITLE
State is missing selectable values in automation

### ISSUE THREAD

**Issue by sasjafor** [astrandb/miele#283]
### The problem

When I try to set up an animation that checks (among other values) the state of a device, the only two selectable values are 'Unknown' and 'Unavailable'.

![image](https://github.com/astrandb/miele/assets/17381598/31597164-38ac-4e7e-b937-eda14bb95c62)

However, there should be others like 'Programmed' or 'Not connected'. Those values are also correctly shown as the value of e.g. sensor.washing_machine_status, but are just not selectable in the automation. Manually entering the name of such a state does not work and the condition always fails to pass, even when the value is exactly what I entered.

My goal is to create an automation that automatically starts miele devices when there is enough surplus power. 

### Version of miele integration having the issue?

miele-0.1.14

### Version of Home Assistant Core having the issue?

core-2023.6.1

**Comment by astrandb** [comment]
There is no support for UI-selectable states (a.k.a device automations) in this integration.
Please try to switch to yaml mode in the automation editor and enter one of following states n.b. lower case only:
```python
# Define various states
STATE_STATUS = {
    0: "reserved",
    STATE_STATUS_OFF: "off",
    STATE_STATUS_ON: "on",
    STATE_STATUS_PROGRAMMED: "programmed",
    STATE_STATUS_WAITING_TO_START: "waiting_to_start",
    STATE_STATUS_RUNNING: "running",
    STATE_STATUS_PAUSE: "pause",
    STATE_STATUS_PROGRAM_ENDED: "program_ended",
    STATE_STATUS_FAILURE: "failure",
    STATE_STATUS_PROGRAM_INTERRUPTED: "program_interrupted",
    STATE_STATUS_IDLE: "idle",
    STATE_STATUS_RINSE_HOLD: "rinse_hold",
    STATE_STATUS_SERVICE: "service",
    STATE_STATUS_SUPERFREEZING: "superfreezing",
    STATE_STATUS_SUPERCOOLING: "supercooling",
    STATE_STATUS_SUPERHEATING: "superheating",
    STATE_STATUS_SUPERCOOLING_SUPERFREEZING: "supercooling_superfreezing",
    STATE_STATUS_NOT_CONNECTED: "not_connected",
}
```

**Comment by sasjafor** [comment]
Thank you for the quick answer! I will try that and report back.

**Comment by aturri** [comment]
Hi @sasjafor 
This may be interesting for you: https://github.com/astrandb/miele/discussions/259

**Comment by sasjafor** [comment]
Ok, thank you for the help. Using lowercase 'programmed' works for detecting the correct state!
