### ISSUE TITLE
After HA update Miele Integration won't load

### ISSUE THREAD

**Issue by Nohchiyco** [astrandb/miele#284]
### The problem

Hello all,

After HA update Miele Integration wan't load. I got an error
"ERROR (MainThread) [custom_components.miele] Unexpected error fetching miele data: module 'flatdict' has no attribute 'FlatterDict'"
Reinstalled many times but no success. Miele client_id, client_secret seems to be correct because when installing miele integration there is a message like "authentication is successful". Tried the solution with deleting .miele-token-cache but still not working.

Is there any way to resolve this problem?

Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.2

Thanks

### Version of miele integration having the issue?

0.1.14

### Version of Home Assistant Core having the issue?

2023.06.2

### Anything in the logs that might be useful for us?

```txt
AttributeError:` module 'flatdict' has no attribute 'FlatterDict'
2023-06-19 00:06:41.684 ERROR (MainThread) [custom_components.miele] Unexpected error fetching miele data: module 'flatdict' has no attribute 'FlatterDict'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 242, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miele/__init__.py", line 295, in async_fetch
```

**Comment by astrandb** [comment]
The installation of the requirement "flatdict" is obviously corrupt. 
Just to clarify: Did you upgrade from "the other" Miele integration to this one?
In any case, uninstall the integration from the UI and then remove all traces of the integration from custom_components/miele, restart HA and then start over to download the integration (with HACS), restart HA again, install the integration and it should be OK.

**Comment by Nohchiyco** [comment]
Yes there was another Miele integration previously installed, but it has been removed before installing this one. The problem came after HA core update. Tried your solution but unfortunately  it didn't help. The problem seems to be in the HAOS installation itself. Something broke after the update. I had to reinstall HAOS and everything worked as before. Thank you.
