### ISSUE TITLE
HA Log full of "WARNING (MainThread) [pymiele.pymiele] Connection was closed, restarting"

### ISSUE THREAD

**Issue by iculookn** [astrandb/miele#286]
### The problem

Hello
I am getting the following error in the HA Logs. at least 5 in a minute so it filling my logs.

`"WARNING (MainThread) [pymiele.pymiele] Connection was closed, restarting"
`

Everything seems to be working with the integration, so not sure why I am getting these messages. Any help would be appreciated

Thanks

### Version of miele integration having the issue?

0.1.14

### Version of Home Assistant Core having the issue?

 2023.6.2

### Anything in the logs that might be useful for us?

```txt
WARNING (MainThread) [pymiele.pymiele] Connection was closed, restarting
```

**Comment by olympia** [comment]
I am getting these as well. @astrandb is this "expected"/ normal behavior or this is something due to our side?

**Comment by astrandb** [comment]
@olympia I wouldn't say it is expected, I have never seen it myself in my production or development systems. 
The message is just a warning that the data stream from the Miele API timed out and that the integration restarted the connection.

**Comment by astrandb** [comment]
Stale issue - closing
