### ISSUE TITLE
not possible to reinstall Miele integration and setup again

### ISSUE THREAD

**Issue by hubdihubdi** [astrandb/miele#287]
### The problem

First the setup worked fine. But I noticed I wrote the client id wrong. So of corse the website said invalid id. 
So I reinstaled the integration. I started wo setup the integration again. 
And here is the problem. The setup automatically goes to the point where the Miele website opens. And there of corse is still the wrong client id. 
I can't co back to the setup point where I write the client id and secret. 
I reinstalled the integration multiple times. Even restarted the hole system. 

### Version of miele integration having the issue?

1.14

### Version of Home Assistant Core having the issue?

Operating System 10.3, Home Assistant 2023.6.3

**Comment by astrandb** [comment]
Goto Settings->Integrations and open the 3-dot menu. There you can delete the stored credentials.

**Comment by hubdihubdi** [comment]
it worked. Thanks.
