### ISSUE TITLE
Setup works fine - integration does not

### ISSUE THREAD

**Issue by apedance** [astrandb/miele#290]
### The problem

As stated above.

I can setup just fine.
Component keeps retrying setup and fails every time spitting out provided logs.

Best regards

### Version of miele integration having the issue?

v0.1.14

### Version of Home Assistant Core having the issue?

Home Assistant 2023.7.2

### Anything in the logs that might be useful for us?

```txt
2023-07-14 12:41:07.218 ERROR (MainThread) [custom_components.miele] Timeout fetching miele data

This error originated from a custom integration.

Logger: custom_components.miele
Source: helpers/update_coordinator.py:262
Integration: Miele (documentation, issues)
First occurred: 12:37:14 (7 occurrences)
Last logged: 12:43:51

Timeout fetching miele data
Error fetching miele data: 'int' object is not iterable
```

**Comment by dolodobendan** [comment]
They changed it to 14h (CEST).

**Comment by dgeisse** [comment]
It took a while, but now everything is back to normal

**Comment by magicdominic** [comment]
official app says maintenance is prolonged until 18:00

**Comment by neildsb** [comment]
Still a problem in the UK, note on APP 'maintenance' until 18:00

**Comment by dolodobendan** [comment]
Still no joy here. "11:21" doesn't really have scheduled maintenance vibes, does it.

**Comment by apedance** [comment]
Works fine. 
Perfect timing when installing into biggest maintenance window..
