### ISSUE TITLE
Getting no infos from Hob most of the time - hangs in state "not connected"

### ISSUE THREAD

**Issue by git-pbf** [astrandb/miele#298]
### The problem

Hob is changing state to "nicht mehr verfügbar" or "not connected" - most of the time HA isn´t able to connect.

### Version of miele integration having the issue?

miele-v0.1.14

### Version of Home Assistant Core having the issue?

2023.7.3

### Additional information

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.7.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.4",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.1.21-v8",
    "supervisor": "2023.07.1",
    "host_os": "Home Assistant OS 10.3",
    "docker_version": "23.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "miele": {
      "version": "0.1.14",
      "requirements": [
        "flatdict==4.0.1",
        "pymiele==0.1.6"
      ]
    },
    "alexa_media": {
      "version": "4.6.5",
      "requirements": [
        "alexapy==1.26.8",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "miele",
    "name": "Miele",
    "codeowners": [
      "@astrandb"
    ],
    "config_flow": true,
    "dependencies": [
      "application_credentials",
      "http"
    ],
    "documentation": "https://github.com/astrandb/miele",
    "homekit": {},
    "integration_type": "hub",
    "iot_class": "cloud_push",
    "issue_tracker": "https://github.com/astrandb/miele/issues",
    "loggers": [
      "pymiele"
    ],
    "requirements": [
      "flatdict==4.0.1",
      "pymiele==0.1.6"
    ],
    "ssdp": [],
    "version": "0.1.14",
    "zeroconf": [],
    "is_built_in": false
  },
  "data": {
    "info": {
      "manufacturer": "Miele",
      "model": "KMDA7476"
    },
    "data": {
      "ident|type|key_localized": "Device type",
      "ident|type|value_raw": 74,
      "ident|type|value_localized": "Hob with vapour extraction",
      "ident|deviceName": "",
      "ident|protocolVersion": 2,
      "ident|deviceIdentLabel|fabNumber": "**REDACTED**",
      "ident|deviceIdentLabel|fabIndex": "00",
      "ident|deviceIdentLabel|techType": "KMDA7476",
      "ident|deviceIdentLabel|matNumber": "11712780",
      "ident|deviceIdentLabel|swids|0": "5579",
      "ident|deviceIdentLabel|swids|1": "20577",
      "ident|deviceIdentLabel|swids|2": "25368",
      "ident|deviceIdentLabel|swids|3": "5621",
      "ident|deviceIdentLabel|swids|4": "20314",
      "ident|deviceIdentLabel|swids|5": "25128",
      "ident|deviceIdentLabel|swids|6": "5621",
      "ident|deviceIdentLabel|swids|7": "20314",
      "ident|deviceIdentLabel|swids|8": "25128",
      "ident|xkmIdentLabel|techType": "EK039W",
      "ident|xkmIdentLabel|releaseVersion": "02.72",
      "state|ProgramID|value_raw": null,
      "state|ProgramID|value_localized": "",
      "state|ProgramID|key_localized": "Program name",
      "state|status|value_raw": 255,
      "state|status|value_localized": "Not connected",
      "state|status|key_localized": "status",
      "state|programType|value_raw": null,
      "state|programType|value_localized": "",
      "state|programType|key_localized": "Program type",
      "state|programPhase|value_raw": null,
      "state|programPhase|value_localized": "",
      "state|programPhase|key_localized": "Program phase",
      "state|remainingTime": {},
      "state|startTime": {},
      "state|targetTemperature": {},
      "state|coreTargetTemperature": {},
      "state|temperature": {},
      "state|coreTemperature": {},
      "state|remoteEnable|fullRemoteControl": false,
      "state|remoteEnable|smartGrid": false,
      "state|remoteEnable|mobileStart": null,
      "state|ambientLight": null,
      "state|light": null,
      "state|elapsedTime": {},
      "state|spinningSpeed|unit": "rpm",
      "state|spinningSpeed|value_raw": null,
      "state|spinningSpeed|value_localized": null,
      "state|spinningSpeed|key_localized": "Spin speed",
      "state|dryingStep|value_raw": null,
      "state|dryingStep|value_localized": "",
      "state|dryingStep|key_localized": "Drying level",
      "state|ventilationStep|value_raw": null,
      "state|ventilationStep|value_localized": "",
      "state|ventilationStep|key_localized": "Fan level",
      "state|plateStep": {},
      "state|ecoFeedback": null,
      "state|batteryLevel": null
    },
    "actions": {
      "processAction": [],
      "light": [],
      "ambientLight": [],
      "startTime": [],
      "ventilationStep": [],
      "programId": [],
      "targetTemperature": [],
      "deviceName": false,
      "powerOn": false,
      "powerOff": false,
      "colors": [],
      "modes": [],
      "runOnTime": []
    },
    "programs": [],
    "id_log": [],
    "local_mappings": {}
  }
}

**Comment by astrandb** [comment]
Stale issue - closing
