### ISSUE TITLE
Authentication failed!  Please check your login details.

### ISSUE THREAD

**Issue by NickWhitNTES** [astrandb/miele#299]
### The problem

I have been trying for months to get this integration to work.

I have an API Client ID and Secret, and they are correct in the config.  However, without fail, I always get this message when doing the authentication:

Authentication failed!

Please check your login details.

### Version of miele integration having the issue?

0.1.14

### Version of Home Assistant Core having the issue?

2023.7.3

**Comment by astrandb** [comment]
Please try the advice here https://github.com/astrandb/miele/discussions/112

**Comment by NickWhitNTES** [comment]
Thank you.  Just before you replied I finally got it working.  For some reason I had to request a new API credential set using a new email.  The original was failing even with the Miele online API test.  

Weirdly.  This was something I tried before.  Second attempt working.  No idea why.
