### ISSUE TITLE
Tumble dryer - remote start

### ISSUE THREAD

**Issue by rploeg** [astrandb/miele#304]
### The problem

The tumble dryer has the possibility to start it remotely (mobile start). I want to see in HA that this program is selected on the dryer, so I can start it when for example the home battery is full or if there is enough energy from the sun. But I cannot see in one of the entities if this program is selected yes or no. Does anybody already have experience with this? 

### Version of miele integration having the issue?

miele-v0.1.14

### Version of Home Assistant Core having the issue?

Home Assistant 2023.8.2

**Comment by aturri** [comment]
Hi,
I have implemented something similar. Here is how: https://github.com/astrandb/miele/discussions/259

Andrea

**Comment by rploeg** [comment]
Thank you. The problem I have, when I put the dryer into mode voor remote start, I don't see anything back (like in your example with programmed -, or waiting to start state):

![image](https://github.com/astrandb/miele/assets/49752333/bd27efa8-9c10-48c2-bd3b-f46c50106222)

**Comment by aturri** [comment]
Hi, 
You should select a program on machine and delay start it. Then the "start at" sensor gets a value and "start" buttons becomes available (the button takes a while).

**Comment by rploeg** [comment]
Ok. Thanks, that is working. So mobile control etc is really only used for setting the program on your mobile phone? Would you advise to use the smart grid function for setting the delayed start or just the normal one?

**Comment by aturri** [comment]
I'm using the SmartStart so I can choose from machine whether to use the automation or just to use a real delay start.
