### ISSUE TITLE
Add support for Miele Dishwasher AutoDos level, Salt level, Rinse Aid level

### ISSUE THREAD

**Issue by ncd7** [astrandb/miele#305]
### Feature request

These levels are available from the native Miele app and so might be exposed via the API.
I could also give it a stab if no one has the time / desire but wanted to first ask in case anyone has any background on this (e.g. that it would be pointless to try because it's not possible). Thanks!

### What version of the integration are you using?

0.1.14

**Comment by aturri** [comment]
Unfortunately the API used by mobile/Alexa/GoogleHome apps is private and different from public API. The requested data are not available in public API. Same story for TwinDos level in washing machines.

**Comment by aturri** [comment]
You could write them an email for a feature request 😃 

However I've implemented a way to estimate the levels of TwinDos for the washing machine. I've found which is the consumption used by machine from the two cartridges and I've set up an input number that is decreased each time I start a cycle.
For rinse aid should be easier because the quantity is fixed for each cycle 😉

**Comment by chochb** [comment]
> You could write them an email for a feature request 😃
> 
> However I've implemented a way to estimate the levels of TwinDos for the washing machine. I've found which is the consumption used by machine from the two cartridges and I've set up an input number that is decreased each time I start a cycle. For rinse aid should be easier because the quantity is fixed for each cycle 😉

Can you share your script or the quantities here? Then I can install it too. Thank you very much!

**Comment by challs** [comment]
> @aturri -- actually where would I make a formal request for the APIs to be exposed? Not that I'm holding my breath but won't hurt to do in parallel.

Hi, I see text on https://www.miele.com/developer/swagger-ui/index.html#/ that lists the email address to use (developer@)
