### ISSUE TITLE
Can't get rid off invalid credentials

### ISSUE THREAD

**Issue by DennisWilken** [astrandb/miele#306]
### The problem

When I first tried to setup the integration, I typed in invalid credentials. Now, I am stuck in the setup process. Whenenever, I start the setup, I am directly refered to a website telling me the connection failed stating my old and invalid client id. I have deleted my browsers cache, reinstalled the integration, used different computers and browser but always directly get the wrong link. I used the tab, logged in via [Swagger](https://www.miele.com/developer/swagger-ui/index.html), replaced the client id from the setup's URL but can't establish a connection. 

I assume the wrong credentials are somewhere stored within HA. How can I delete them and start new?

Thanks for your help!

### Version of miele integration having the issue?

0.1.14

### Version of Home Assistant Core having the issue?

2023.8.3

**Comment by astrandb** [comment]
Goto Settings->Integrations and select the overflow menu (3 dots)

**Comment by DennisWilken** [comment]
I can't find the integration in the integration menu yet because I couldn't sucessfully finish the setup. In the hacs menu, I find the overflow menu but it only offers me the option to re-download which doesn't help.

Thanks for the quick reply!

**Comment by astrandb** [comment]
There should be an overflow meny in Settings->Devices and services . You can also reach the credentials admin page by going directly to <your-ha-url>/config/application_credentials

**Comment by DennisWilken** [comment]
Thanks for clarifying! This solved my issue.
