### ISSUE TITLE
Always redirect with the wrong client id

### ISSUE THREAD

**Issue by unl0ck** [astrandb/miele#314]
### The problem

on the first time I made an issue on the client id.
now always I want to add Miele as device he redirect me directly to the miele website.

I removed in HACS the Integration nothing works.
How can I removed the credentials?

### Version of miele integration having the issue?

V0.1.14

### Version of Home Assistant Core having the issue?

2023.8.4

**Comment by astrandb** [comment]
Please follow the instructions here https://github.com/astrandb/miele/discussions/247

**Comment by unl0ck** [comment]
Sorryyyyyyyyy Thank you
