### ISSUE TITLE
Better icons

### ISSUE THREAD

**Issue by mundschenk-at** [astrandb/miele#33]
### Feature request

There are several Material Design Icons that could be used to give the `*_status` more visual distinctiveness, e.g. `mdi:dishwasher` and `mdi:washing-machine`. This could be extended to the binary sensors for `info` and `error` (there's a corresponding `-alert` variant, e.g. `mdi:dishwasher-alert`). Similar icons also exist for fridges, while for freezers, `mdi:snow` could be used (there are both `-off` and `-alert` variants of it). 

Unfortunately, I've only found one icon for stovetops (`mdi:stove`) which does not have any of the variants. There also doesn't appear to be a specific icon for ovens (although the stove icon could be used, I guess).

### What version of the integration are you using?

miele-0.0.10

**Comment by astrandb** [comment]
Most of this is taken care of on v0.1.4
