### ISSUE TITLE
New amazing tool for translation

### ISSUE THREAD

**Issue by astrandb** [astrandb/miele#331]
### Feature request

We have got the possibility to use [Lokalise](https://lokalise.com) for managing our translations. At this point I would like to invite you @mundschenk-at  and @aturri to join the team. Please follow the instructions here https://github.com/astrandb/miele#translation .
As you will see, there are a few missing translations for your language.
All feed-back is welcome.

Please reply in this issue when you have created your account with Lokalise.

### What version of the integration are you using?

Latest

**Comment by aturri** [comment]
Hi @astrandb, I've joined Lokalise. How do I proceed now?
Thanks!
Andrea

**Comment by astrandb** [comment]
I need the email address that you used when registering. Then I add you to the team. You can email it to me at ake@strandberg.eu

**Comment by astrandb** [comment]
@aturri @mundschenk-at Clicking this link should join you to the project
https://app.lokalise.com/public/50153460650965e9a01e21.29484567/

**Comment by mundschenk-at** [comment]
Yes I've joined now.

**Comment by astrandb** [comment]
Welcome!
Now you can update the translations in Lokalise. 
When I prepare a new release, I just click a button in Lokalise and a PR with all translation changes is automatically created in the github repo.

**Comment by aturri** [comment]
I'm in, thanks! :)

**Comment by ClausSamuelsen** [comment]
Hej Åke
I'd be happy to do a Danish translation. I created a Lokalise account, but it's only a trial account with a duration of 14 days. Hope I don't need to pay for using Lokalise,

**Comment by astrandb** [comment]
@ClausSamuelsen Welcome to the translation team. I have added Danish language. Click this link to join the project: https://app.lokalise.com/public/50153460650965e9a01e21.29484567/

There is no cost for participating in this project, Thanks to the generosity of Lokalise.

When it comes to program names, program phases etc, try to use same terminology as Miele uses on the device panel, in the manual or in the app.

**Comment by ClausSamuelsen** [comment]
@astrandb Would it be possible in Lokalise to have info about which product group a word og phrase belongs to (e.g. washing machines, freezers etc).
Danish translation should be ready now.

**Comment by astrandb** [comment]
@ClausSamuelsen Thank you for your contribution. The Danish translation will be included in next release of the integration.

Well, it is possible to add comments to each key, but it can be cumbersome to maintain. The information you ask for is present in the const.py file.

**Comment by mundschenk-at** [comment]
@astrandb I've updated the German translation (and fixed some issues I missed during the previous round). While doing so, I've noticed some errors in the English "translation" for some of the constants, namely there are several instances where `supercooling/superfreezing` is "translated" as `supercooling/superheating`. I wanted to fix that, but apparently I can't change the English strings.

**Comment by astrandb** [comment]
@mundschenk-at Thank you. I don't know what I was thinking about when typing superheating. ;-)

**Comment by rudizl** [comment]
@astrandb About fridge with integrated oven :)

**Comment by Amaurgit** [comment]
Hey ! Just joined and contributed to some french translations  :)

**Comment by astrandb** [comment]
@Amaurgit Thank you, Your work will be included in next release of the integration.

**Comment by ExMacro** [comment]
> Is there already a Finnish (as in Finland) translations included in the Miele integration? If not, I'd be happy to join the project to do that.

.. I've joined Lokalise and added myself to the Finnish team. That was easy!

**Comment by astrandb** [comment]
Welcome. I added Finnish 1 minute ago!

**Comment by astrandb** [comment]
Stale issue - closing
