### ISSUE TITLE
Help with updating of translations needed

### ISSUE THREAD

**Issue by astrandb** [astrandb/miele#337]
### Feature request

@aturri @mundschenk-at @geert36 @florie1706 @nagyrobi @palengh @Labu7
I am addressing you as you have previously contributed with translation of the Miele integration for Home Assistant.  There is now a simplified (and more advanced) process for translations using Lokalise.
I would appreciate if you would continute your contribution with some updates.

To join the team in Lokalise, go to https://app.lokalise.com/login and select login with Github.
Then [click here](https://app.lokalise.com/public/50153460650965e9a01e21.29484567/) to join the project. 

You will now get a good overview of the tranlations and any missing strings, and it is easy to update

The updated translations will appear in next release of the integration.

Best,
Åke S, @astrandb

### What version of the integration are you using?

Latest

**Comment by nagyrobi** [comment]
Joined.

**Comment by rudizl** [comment]
Please add bulgarian language.

**Comment by astrandb** [comment]
> Please add bulgarian language.

@rudizl Welcome to the team of translators.

**Comment by nagyrobi** [comment]
@astrandb it would be probably useful to rename `Åke's Team` in Lokalise to something like `Miele custom component` so when we have joined multiple teams, we know the difference.

**Comment by astrandb** [comment]
@nagyrobi The team is tied to my license with Lokalise and it hosts a couple of other translation projects. Renaming the team to something with Miele in the title would just confuse other team members.
However, I shall consider a less egocentric name.

**Comment by aturri** [comment]
Great! I've added missing IT translations :)

**Comment by rudizl** [comment]
> > Please add bulgarian language.
> 
> @rudizl Welcome to the team of translators.

I think I'm ready with the BG translation.

**Comment by MrKohli** [comment]
I've added most of what was missing from the German translation

**Comment by mundschenk-at** [comment]
Hi @astrandb, I've reviewed the German translations (hopefully all). Thanks to @MrKohli for his work, but unfortunately I had to revert most of the program name changes (while they were more correct standard German, these are Miele program names not following standard orthography and syntax).

I also changed the translation of the config flow to follow the informal ("du") instead of the formal ("Sie") mode of address, as that is what the Home Assistant core uses.

**Comment by astrandb** [comment]
Thank you all for your contributions to the translations. It is the joint effort that ensures that we keep up the quality. Translation is is not an exact science and I know from my contacts with developers at Miele that they also have a lot of challenges in this area.
I plan to make a release tomorrow afternoon so there is still time for further fine-tuning. Lokalise will of course always be open for further work but nobody knows when next release is due.

**Comment by bartkummel** [comment]
I've added the missing words & phrases in the Dutch language. And made some small corrections.

**Comment by astrandb** [comment]
Stale issue - closing
