### ISSUE TITLE
Add support for KM7474 hob

### ISSUE THREAD

**Issue by bartkummel** [astrandb/miele#363]
### Feature request

I have a KM7474 4-zone induction hob. I can see it via the Miele integration in HA. However, I can only see if it's on or off. In the Miele app, I can also see which zone is in use, and to what level it is set. Would be nice if I could see that in HA too. (Would even be nicer if I could control it from HA, but it seems Miele doesn't support that via the API at all.)

Let me know if I can be of any help. I have access to the device, I know how to make API calls. 

### What version of the integration are you using?

v0.1.17

**Comment by astrandb** [comment]
Please put a couple of pots on the hob and set the different zones to low, medium and high power. Then create a diagnostic download from the device page and drag the file into this issue. 
As you state there is no support for controlling the heat zones from the API.

**Comment by bartkummel** [comment]
[miele-54a5d1ca089486371e950d3df56302d5-Hob-4a31169ee95a7ed043686c3a9c77edc0.json.txt](https://github.com/astrandb/miele/files/13311855/miele-54a5d1ca089486371e950d3df56302d5-Hob-4a31169ee95a7ed043686c3a9c77edc0.json.txt)
Here's the requested file. Note that this doesn't cover all available power settings, let me know if you need additional info about all other level's that I can set.

**Comment by astrandb** [comment]
Thank you.
The diagnostic file looks like I expected. Can you try to restart Home Assistant while at least one zone is on and catch a new diagnostic when HA is up and running. It might be that KM 7474 is not reporting the number of available zones when all zones are off.

If you set one zone to "keeping warm" and one to boost, I think I have got what I need to add this model.

**Comment by bartkummel** [comment]
[miele-54a5d1ca089486371e950d3df56302d5-Hob-4a31169ee95a7ed043686c3a9c77edc0.json (6).txt](https://github.com/astrandb/miele/files/13328230/miele-54a5d1ca089486371e950d3df56302d5-Hob-4a31169ee95a7ed043686c3a9c77edc0.json.6.txt)
Here's a diagnostics file I captured after a restart, when I had two zones on. One was on "keeping warm", the other on "boost 2". (This hob has two boost levels.)

Regarding the number of zones that might not be reported correctly: this hob has two "flex zones", that could be merged together. Could it be that the incorrect number has to do with that feature?

**Comment by astrandb** [comment]
You can test these latest fixes before official release by redownloading the Miele integration in HACS and then restarting Home Assistant.

> Could it be that the incorrect number has to do with that feature?

No, I think it is a problem in the API. Some recent hob models report no zones at all when the hob is off. Previous models report that the hob is off and that all individual zones off.

**Comment by bartkummel** [comment]
I'll do a test soon! Thanks so much for your work on this!

**Comment by bartkummel** [comment]
I’ve tested `main`. I see 4 zones now and the level of each is displayed correctly. Thanks a lot!!
