### ISSUE TITLE
Device Not Shows up

### ISSUE THREAD

**Issue by TomF79** [astrandb/miele#376]
### The problem

I have already Running a Miele TCF770WP Tumble Dryer with the Integration in HomeAssistant.

Now i have integrated a steam oven Miele DGC7450 in my Miele App but the new device is not showing up in the Integration.

I have reinstalled the Integration and all other steps but the new device Not showing up, only the Tumble Dryer.

What Can i do?

Best Regards
Tom

### Version of miele integration having the issue?

v.0.1.17

### Version of Home Assistant Core having the issue?

2023.11.2

**Comment by astrandb** [comment]
Let's try to catch some debug info:
Please goto <your_ha>/config/integrations/miele and open the "three-vertical-dots" menu. Then select Download diagnostics and drag the diagnostic file into this issue.

**Comment by TomF79** [comment]
> Let's try to catch some debug info: Please goto <your_ha>/config/integrations/miele and open the "three-vertical-dots" menu. Then select Download diagnostics and drag the diagnostic file into this issue.

Here you are

[config_entry-miele-b9e00b3420cd9611e3f1a0ce63b840fc.json.txt.json](https://github.com/astrandb/miele/files/13403408/config_entry-miele-b9e00b3420cd9611e3f1a0ce63b840fc.json.txt.json)

**Comment by astrandb** [comment]
Thank you. 
The oven reports device type 73 which is undocumented in the Miele API. Please refer to: https://www.miele.com/developer/assets/API_V1.x.x_capabilities_by_device.pdf
If you repeat the diagnostic download with the oven turned on, I can add provisional support in the integration until Miele updates the documentation.

**Comment by TomF79** [comment]
> Thank you. The oven reports device type 73 which is undocumented in the Miele API. Please refer to: https://www.miele.com/developer/assets/API_V1.x.x_capabilities_by_device.pdf If you repeat the diagnostic download with the oven turned on, I can add provisional support in the integration until Miele updates the documentation.

I have seen there is no Name in this section:

"ident|type|value_localized": "",

I have turned it on and here the new diagnostic:

[config_entry-miele-b9e00b3420cd9611e3f1a0ce63b840fc.json.txt.json](https://github.com/astrandb/miele/files/13403458/config_entry-miele-b9e00b3420cd9611e3f1a0ce63b840fc.json.txt.json)

**Comment by TomF79** [comment]
Maybe it should be device Type 15

**Comment by astrandb** [comment]
> I have seen there is no Name in this section:
> 
> "ident|type|value_localized": "",

Yes, I have seen that before when new models appear. Miele seems to put most energy into updating the IOS and Android apps with new models. The 3:rd party API usually comes late in the priority queue.

I guess that they have a good reson for creating a new device type.

**Comment by TomF79** [comment]
Thanks for your Support.

Is the new diagnostic file enough for provisional or you Need more?

**Comment by astrandb** [comment]
It looks like the API support is very limited. It reports if the oven is on or off and you can probably control the light inside. I cannot see that you can read or control the temperature.

I will setup a basic oven model and then we just have to wait until Miele fixes the API. 

I can send the developers an email but sometimes it takes many weeks until they answer.

The provisional steam oven support will be included in next release of the integration.

**Comment by TomF79** [comment]
Thank you very much.

Hopefully they will integrate it soon as possible.

**Comment by TomF79** [comment]
> It looks like the API support is very limited. It reports if the oven is on or off and you can probably control the light inside. I cannot see that you can read or control the temperature.
> 
> I will setup a basic oven model and then we just have to wait until Miele fixes the API.
> 
> I can send the developers an email but sometimes it takes many weeks until they answer.
> 
> The provisional steam oven support will be included in next release of the integration.

I have turned the oven on and started a program and downloaded again the diagnostic file. I think there is more than before, please Look in it.

[config_entry-miele-b9e00b3420cd9611e3f1a0ce63b840fc.json.txt.json](https://github.com/astrandb/miele/files/13403519/config_entry-miele-b9e00b3420cd9611e3f1a0ce63b840fc.json.txt.json)

**Comment by astrandb** [comment]
@TomF79 It looks like it behaves that other ovens. I have just merged a PR with basic support for this model. You can test the new version if you go to HACS, redownload the Miele integration - select `version main` and restart HA.

**Comment by astrandb** [comment]
I just realized that program names need some more love. The mappoing of numbers to clear text is not documented but we have been able to catch following so far:
```
    -1: "no_program",  # Extrapolated from other device types.
    0: "no_program",  # Extrapolated from other device types
    1: "defrost",
    6: "eco_fan_heat",
    7: "auto_roast",
    10: "full_grill",
    11: "economy_grill",
    13: "fan_plus",
    14: "intensive_bake",
    19: "microwave",
    24: "conventional_heat",
    25: "top_heat",
    29: "fan_grill",
    31: "bottom_heat",
    49: "moisture_plus_fan_plus",
    512: "1_tray",
    513: "2_trays",
    529: "baking_tray",
    "unmapped_1": "steam_bake",
    17003: "no_program",
```
If you have som time to spend you are most welcome help with updating the list.

**Comment by TomF79** [comment]
> I just realized that program names need some more love. The mapping of numbers to clear text is not documented but we have been able to catch following so far:
> 
> ```
>     -1: "no_program",  # Extrapolated from other device types.
>     0: "no_program",  # Extrapolated from other device types
>     1: "defrost",
>     6: "eco_fan_heat",
>     7: "auto_roast",
>     10: "full_grill",
>     11: "economy_grill",
>     13: "fan_plus",
>     14: "intensive_bake",
>     19: "microwave",
>     24: "conventional_heat",
>     25: "top_heat",
>     29: "fan_grill",
>     31: "bottom_heat",
>     49: "moisture_plus_fan_plus",
>     512: "1_tray",
>     513: "2_trays",
>     529: "baking_tray",
>     "unmapped_1": "steam_bake",
>     17003: "no_program",
> ```
> 
> If you have som time to spend you are most welcome help with updating the list.

How Cani help you with this list?

**Comment by astrandb** [comment]
> How can I help you with this list?

You need to install the latest dev version (main) of the integration. Then you can see the active program and the active program phase on the device page. Numeric values will be displayed if the actual names are unknown to the integration. E.g. "13" instead of "Fan plus".
You can enter new codes here or better for me  - submit a PR. Constants can be found in const.py and english clear text mapping in translations/en.json.

**Comment by TomF79** [comment]
Ok i will Look into that in the next days. Many thanks.

**Comment by TomF79** [comment]
I hope this helps.

13 - Heißluft
24 - Ober- und Unterhitze
361 - Dampfgaren
7 - Bratautomatik
14 - Intensivbacken
10 - Grill groß
29 - Umluftgrill
35 - Klimagaren + Bratautomatik
40 - Klimagaren + Heißluft plus
74 - Klimagaren + Intensivbacken
76 - Klimagaren + Ober- und Unterhitze
31 - Unterhitze
6 - Eco Heißluft
356 - Auftauen
357 - Dörren
358 - Geschirr wärmen
621 - Germteig 15
622 - Germteig 30
623 - Germteig 45
362 – Warmhalten

**Comment by astrandb** [comment]
Many thanks.

**Comment by TomF79** [comment]
It already looks quite good and works.

<img width="384" alt="Bildschirmfoto 2023-11-20 um 09 11 29 jpeg" src="https://github.com/astrandb/miele/assets/93859783/97d41647-d846-400c-b187-dd2f590f4ff0">

**Comment by TomF79** [comment]
Another one in Action. Thanks for your Support.

![Uploading Bildschirmfoto 2023-11-20 um 10.48.57.jpeg.png…]()

**Comment by astrandb** [comment]
It looks good. 
This oven may also have unknown values for Programmabschnitt. Please report if you see any numeric values there.

I would like to see if it is possible to set Zieltemperatur from the integration.
Please select a "normal" program like Ober-/Unterhitze and start the oven.  If your oven has a food temperature probe, please connect it. Then capture a diagnostic download.

**Comment by TomF79** [comment]
Here you are.

[config_entry-miele-61a10257216515569043355a5b4d1cc3.json.txt.json](https://github.com/astrandb/miele/files/13412901/config_entry-miele-61a10257216515569043355a5b4d1cc3.json.txt.json)

I dont have a temperature probe to test it.

I would look to find values for Programmabschnitt.

**Comment by TomF79** [comment]
<img width="255" alt="Bildschirmfoto 2023-11-20 um 11 46 08 jpeg" src="https://github.com/astrandb/miele/assets/93859783/91d9ea01-5384-4958-9651-a6c8fc72d0cd">
<img width="255" alt="Bildschirmfoto 2023-11-20 um 11 45 28 jpeg" src="https://github.com/astrandb/miele/assets/93859783/7778ba8e-8c0e-4f9e-bfcb-dc032475ac4c">

**Comment by astrandb** [comment]
OK. If you see a numeric value as Programmabschnitt then you can report it. "unbekannt" is probably correct in this context.

The API indicates that it does not accept the setting of target temperatures so I think the integration is as complete as possible right now.

I will make a new release of the integration within a few days. Thank you for your collaboration.

**Comment by astrandb** [comment]
You can stay on the main version you have for now.
When a new release is available, update and reinstall will do the same thing. I recommend that you switch over to the stable release when a new release becomes available. The head of "main" is normally just used for pre-release testing an can contain debugging code and other tests that are not suited for distribution.
