### ISSUE TITLE
Entities gone on Miele Washing Machine on XKM3000Z after Update

### ISSUE THREAD

**Issue by awor** [astrandb/miele#379]
### The problem

Hello
First of all, many thanks for this integration! 
I recently updated to latest v0.1.17. I had skipped quite a few versions previously (not sure what the original version was). Now all entities of the washing machine are showing
`This entity is no longer being provided by the miele integration. If the entity is no longer in use, delete it in settings.`
The washing machine is connected via XKM3000Z gateway. The tumbler, which is connected via WLAN is still working fine.
Is the gateway not supported any longer?

### Version of miele integration having the issue?

v0.1.17.

### Version of Home Assistant Core having the issue?

2023.11.0

### Anything in the logs that might be useful for us?

```txt
sorry, couldn't find anything...
```

**Comment by astrandb** [comment]
The integration doesn't care if the connection goes through a gateway or directly via WiFi. It just reads what the Miele Cloud API serves.

You can get some diagnostic data by going to <your_ha>/config/integrations/miele and open the "three-vertical-dots" menu. Then select Download diagnostics and drag the diagnostic file into this issue.

**Comment by astrandb** [comment]
A quick look shows nothing odd. What is displayed on the integration page <your_ha>/config/integrations/integration/miele ?
How many devices, how many entities ?

**Comment by awor** [comment]
<img width="516" alt="image" src="https://github.com/astrandb/miele/assets/3464535/f9c47b77-e36b-4c3a-8bc9-4dab9a768ec6">
What is weird is that the washing machine is in there twice:
<img width="1249" alt="image" src="https://github.com/astrandb/miele/assets/3464535/95c2a170-0ee5-4548-96e2-42eb531f7b5f">
All the sensors are unavailable
<img width="675" alt="image" src="https://github.com/astrandb/miele/assets/3464535/e7b6b738-f24b-44f1-954f-f24edffcca7c">
Both devices are visible and responsive in app:
<img width="357" alt="image" src="https://github.com/astrandb/miele/assets/3464535/56ebab0a-db0e-4fbc-88b3-836cab0bf70b">
If you can't see anything wrong, do you think I need to reinstall the integration?

**Comment by astrandb** [comment]
> If you can't see anything wrong, do you think I need to reinstall the integration?

I think some garbage data has sneaked in at some point in time. Please remove the integration and add it back. If you are prompted to remove your application credentials, you can choose to keep them. It simplifies the reinstall.

**Comment by awor** [comment]
Hi, I upgraded from 17 to the latest 19 version, deleted and reinstalled the integration as you suggested. The "phantom" washing machine is now gone and everything appears to be working again. Many thanks for your support!
