### ISSUE TITLE
The appliance KM7464 is not fully supported

### ISSUE THREAD

**Issue by matsahm** [astrandb/miele#384]
### The problem

Since Version 0.1.18 i have the following Error-Message in Home Assistant:
The appliance type KM7464 is not fully supported by the Miele integration. Therefore some entities might be missing or malfunctioning.

### Version of miele integration having the issue?

0.1.18

### Version of Home Assistant Core having the issue?

2023.11.2

### Anything in the logs that might be useful for us?

```txt
No
```

**Comment by iculookn** [comment]
also getting the same error. cant find anything in the logs apart from 

`[pymiele.pymiele] Connection was closed, restarting` (but I have been getting that error for a long time)



![miele](https://github.com/astrandb/miele/assets/8793442/33400aa0-0bba-44f9-aa31-605a913aff45)

**Comment by astrandb** [comment]
Thank you for reporting. The model codes will be updated in next release.

@iculookn The `connected/restarting`is just a warning message. It indicates that there has been a glitch in the connection between your HA and the Miele cloud servers.

**Comment by ToDv2304** [comment]
Hello, I have similar error report:
The appliance KM7667 R01 is not fully supported

**Comment by astrandb** [comment]
Thank you for reporting. 
Please create a new issue if you get warnings in the log regarding inconsistent number of heat zones.
