### ISSUE TITLE
The appliance KMDA7476 is not fully supported

### ISSUE THREAD

**Issue by apronk1971** [astrandb/miele#385]
### The problem

The appliance type KMDA7476 is not fully supported by the Miele integration. Therefore some entities might be missing or malfunctioning.

Please report this issue to [the maintainer on Github](https://github.com/astrandb/miele/issues)

### Version of miele integration having the issue?

v0.1.18

### Version of Home Assistant Core having the issue?

2023.11.2

### Anything in the logs that might be useful for us?

```txt
Will share when needed
```

**Comment by requiemmg** [comment]
Same for device KM7697. Did not want to open a new thread for each device.

**Comment by hugendudel** [comment]
Same for me with a KMDA7476, would be a pleasure to support you with information.

Thanks

**Comment by astrandb** [comment]
Thank you for reporting. 
Please create a new issue if you get warnings in the log regarding inconsistent number of heat zones.
