### ISSUE TITLE
The appliance KM7897 R01 is not fully supported

### ISSUE THREAD

**Issue by 2confirm** [astrandb/miele#386]
### The problem

After updating the Miele integration to version 0.1.18 I get the message: The appliance KM7897 R01 is not fully supported

### Version of miele integration having the issue?

0.1.18

### Version of Home Assistant Core having the issue?

2023.11.2

### Anything in the logs that might be useful for us?

```txt
Can supply this if deemed necessary
```

**Comment by Biab999** [comment]
Same for: The appliance KMDA7633 is not fully supported

The appliance type KMDA7633 is not fully supported by the Miele integration. Therefore some entities might be missing or malfunctioning.

**Comment by tag6** [comment]
Same for me with our hob:

_Das Gerät KM7678 wird derzeit nicht vollständig unterstützt._

Guess it does not really matter that the message is German. It means the same.

**Comment by astrandb** [comment]
Thank you for reporting. 
Please create a new issue if you get warnings in the log regarding inconsistent number of heat zones.
