### ISSUE TITLE
Washing Machine consumption 

### ISSUE THREAD

**Issue by guggu1** [astrandb/miele#389]
### The problem

for my Miele washing machine water and energy consumption are tagged as "disabled by integration"
Miele data:
Model: WWG360
Firmware: 03.97
Hardware: EK037
Serial number: 000151551160

I run another home automation based on ioBroker. there, the consumption data are available. Hence I guess the probelm is not on the miele side.

CCS

### Version of miele integration having the issue?

v0.1.19

### Version of Home Assistant Core having the issue?

core and supervisor: 2023.11.3. Operating System: 11.1. Frontend:20231030.2

### Anything in the logs that might be useful for us?

```txt
see screenshot below
```

### Additional information

![image](https://github.com/astrandb/miele/assets/23314447/64f922d4-025a-4e32-98a0-49e30c4399a5)

**Comment by astrandb** [comment]
These entities are disbled by default because they dont work with all washing machine models. You must enable the entities that you want to see. Open the entity card and click the cog-wheel.

**Comment by guggu1** [comment]
thanks. That was quick. And it works.
Should I have known the solution?

CCS

**Comment by astrandb** [comment]
> Should I have known the solution?

Well, it is described here https://github.com/astrandb/miele/wiki/Design#general-design-philosophy (bullet 4).

Anyway... Now you know.
