### ISSUE TITLE
Error: Config flow could not be loaded

### ISSUE THREAD

**Issue by RadianM** [astrandb/miele#399]
### The problem

While installing the integration using HACS and after entering our credentials the following error message appeared:

![Screenshot 2023-12-16 15 30 07](https://github.com/astrandb/miele/assets/13075243/18214335-7c40-413b-907d-476dc3dc0d5f)

Afterwards the integration appears to have loaded and shows our username under Hubs - but no devices or entities are listed. 

![Screenshot 2023-12-16 17 05 33](https://github.com/astrandb/miele/assets/13075243/d3d4323a-076c-4e3f-a1f9-8e501667845c)

It's unclear if this has anything to do with the error message above - or if our model of smart dishwasher isn't supported by this integration (Miele g7165). 

### Version of miele integration having the issue?

v0.1.19

### Version of Home Assistant Core having the issue?

2023.12.3

### Anything in the logs that might be useful for us?

```txt
The only relevant entry in the logs is regarding a timeout:

2023-12-16 16:53:15.354 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-16 16:53:15.356 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration daikin_residential which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-16 16:53:15.357 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration miele which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-16 17:04:23.357 ERROR (MainThread) [custom_components.miele] Timeout fetching miele data
```

**Comment by astrandb** [comment]
The initial error "invalid flow specified" is a bit uncommon. I suggest that you remove the integration, if asked to remove the credentials, answer yes.  Then restart HA and install it again. 
It is 7 minutes between start of HA and the timeout error so the latter is probably caused by the Miele servers.

**Comment by RadianM** [comment]
I deleted our credentials and removed the integration, restarted and installed again.
On restarting, having re-installed the integration, I went to configure it and suprisingly this message popped up:
![Screenshot 2023-12-16 18 10 37](https://github.com/astrandb/miele/assets/13075243/32269f36-76b3-4514-b19b-65d718677968)
This is before any credentials have been supplied (this time around) yet it knows my model of dishwasher!
Regardless, I continued on and entered the creds but the No devices or entities message still shows under Hubs.

**Comment by astrandb** [comment]
This dialog appears when the device broadcasts its existence on the LAN so it does not say anything about if it is available in the API. 

Can you see your device in the Miele app? 

Please get a diagnostic download from the Miele integration overview page - three dot menu and upload the file here.

**Comment by RadianM** [comment]
Ah that makes sense. Yes it appears in the app OK. Here's the json:
[config_entry-miele-30788b951f1e366b6e1bac388fefb873.json.txt](https://github.com/astrandb/miele/files/13693736/config_entry-miele-30788b951f1e366b6e1bac388fefb873.json.txt)

**Comment by RadianM** [comment]
Poking around a bit more today, I ended up putting our credentials into [https://www.miele.com/developer/swagger-ui/#/Information/getDevices](https://www.miele.com/developer/swagger-ui/#/Information/getDevices) which I guess lets me try their api for real (?) Anyway, the result of GET/devices was:

response body
`{}`

So no devices on our account?
Yet the Miele app works just fine!

**Comment by astrandb** [comment]
Ok, there is obviously a problem with your account. My advice is to contact Miele support.

**Comment by RadianM** [comment]
OK, many thanks.

**Comment by RadianM** [comment]
Deleted account, made a different one, and all is working now.
