### ISSUE TITLE
id_log diagnostics not recorded correctly

### ISSUE THREAD

**Issue by mundschenk-at** [astrandb/miele#40]
### The problem

The `id_log` key in HA diagnostics should display raw and localized values for `stateProgramPhase`, `stateProgramID` and `stateProgramType`. In practice, `stateProgramPhase` appears to be the only logged `key`, with `raw` value consistent with with that `key`. However, `localized` is clearly from `stateProgramID`.

### Version of miele integration having the issue?

miele-0.0.11

### Version of Home Assistant Core having the issue?

core-2022.2.6

### Anything in the logs that might be useful for us?

```txt
"id_log": [
      {
        "appliance": "Dishwasher",
        "key": "stateProgramPhase",
        "raw": 1792,
        "localized": "Automatic"
      },
      {
        "appliance": "Washer dryer",
        "key": "stateProgramPhase",
        "raw": 256,
        "localized": ""
      },
      {
        "appliance": "Dishwasher",
        "key": "stateProgramPhase",
        "raw": 1792,
        "localized": "Automatic"
      },
      {
        "appliance": "Washer dryer",
        "key": "stateProgramPhase",
        "raw": 256,
        "localized": ""
      },
      {
        "appliance": "Dishwasher",
        "key": "stateProgramPhase",
        "raw": 1792,
        "localized": "Automatic"
      },
```

**Comment by mundschenk-at** [comment]
Something funky's still going on - I got no `log_id` entries for `stateProgramID` at all.

**Comment by astrandb** [comment]
The logging code might be in sub-optimal place, where it is depending on what the frontend is doing. I will have a look tonight or tomorrow.

**Comment by mundschenk-at** [comment]
Yes it seems to record the same things over and over again. Also, should the log not be unique to each device? Currently the list is mixed.

**Comment by astrandb** [comment]
This logging function is not good enough to be left in the backgound. To be really effective it should subscribe to events from the status sensor when the status is changed and log appropriate data. This is not a trivial fix for me, but should be doable if time allows.
