### ISSUE TITLE
Edit/Delete ClienID/Secret

### ISSUE THREAD

**Issue by pacco81** [astrandb/miele#418]
### The problem

Hi !

At first install I had an typo in the ClienID/Secret input. I uninstalled Miele in HACS and installed it new.

When I start the configuration Steps now, I am not asked for the ClienID/Secret again but will be directed to the miele-Homepage immediately. 

How do I delete or edit the ClienID/Secret ? Where are they stored ?

Thank you ! 

### Version of miele integration having the issue?

0.1.21

### Version of Home Assistant Core having the issue?

2024.1.5

**Comment by astrandb** [comment]
See here: https://github.com/astrandb/miele/discussions/247

**Comment by pacco81** [comment]
Ah Ok ! Thank you.
Maybe the steps could be implemented into the Wiki/FAQ.
