### ISSUE TITLE
0Auth error

### ISSUE THREAD

**Issue by waraf** [astrandb/miele#443]
### The problem

When installing  the Miele integration in the last step i am getting the following error:
0Auth authorization error while obtaining access token

### Version of miele integration having the issue?

V 2024.1.0

### Version of Home Assistant Core having the issue?

2024.4.5

**Comment by astrandb** [comment]
Probaby something wrong with your entered client_id, client_secret or password.
Note that the Miele API does not accept special characters in the password.
Try to start over. https://github.com/astrandb/miele/discussions/247

**Comment by waraf** [comment]
problem solved  

Thx
