### ISSUE TITLE
Support for Miele appliances announcing their presence with service `_mielesemiprof._tcp`

### ISSUE THREAD

**Issue by arrelid** [astrandb/miele#444]
### Feature request

Some Miele appliances announce their presence over `_mielesemiprof._tcp` rather than `_mieleathome._tcp`.

```sh
❱ dns-sd -B _mieleathome._tcp
Browsing for _mieleathome._tcp
DATE: ---Sat 02 Mar 2024---
10:15:59.747  ...STARTING...
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
10:15:59.749  Add        3  11 local.               _mieleathome._tcp.   Miele WWV980
10:15:59.749  Add        3  13 local.               _mieleathome._tcp.   Miele WWV980
10:15:59.749  Add        3  11 local.               _mieleathome._tcp.   Miele TWV680WP
10:15:59.749  Add        3  13 local.               _mieleathome._tcp.   Miele TWV680WP
...
^C⏎
❱ dns-sd -B _mielesemiprof._tcp
Browsing for _mielesemiprof._tcp
DATE: ---Sat 02 Mar 2024---
10:16:04.746  ...STARTING...
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
10:16:04.747  Add        3  11 local.               _mielesemiprof._tcp. Miele PG8133
10:16:04.747  Add        2  13 local.               _mielesemiprof._tcp. Miele PG8133
^C⏎
```

Have you stumbled upon these before? They're readily available in the Miele app on iOS, and it would be lovely if these could be supported (notifications when dishes are done...).

### What version of the integration are you using?

2024.2.0b2

**Comment by astrandb** [comment]
The discovery info above just announces that a Miele appliance is present on the LAN. This info is used to trigger a configuration flow if the integration is not already set up. As far as I know there is no other info broadcasted on the LAN, at least not documented by Miele. This integration uses the public 3rd party API. I know that some appliances from the semi-pro series appear in the API and thus in the integration. Is this the case with PG8133? If not, I dont think we should  detect these devices and trigger a config flow as the result would just be disapointing to the user.

**Comment by arrelid** [comment]
> I know that some appliances from the semi-pro series appear in the API and thus in the integration. Is this the case with PG8133? If not, I dont think we should detect these devices and trigger a config flow as the result would just be disapointing to the user.

Good point - didn't think about the discovery vs actual request of devices from the official API. Querying `'https://api.mcs3.miele.com/v1/short/devices` I don't see any of "my" semi-pro devices in there :/

Case closed, I guess.
