### ISSUE TITLE
Miele integration does not set supported color modes

### ISSUE THREAD

**Issue by ExMacro** [astrandb/miele#446]
### The problem

After installing HA2024.3, the Miele integration gets a warning. One year time to fix this it seems:

### Version of miele integration having the issue?

2024.1.0

### Version of Home Assistant Core having the issue?

2024.3

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.light
Source: components/light/__init__.py:1269
integration: Light (documentation, issues)
First occurred: 17:16:14 (1 occurrences)
Last logged: 17:16:14

None (<class 'custom_components.miele.light.MieleLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/astrandb/miele/issues
```

### Additional information

No hurry, just thought I'd report this.

**Comment by astrandb** [comment]
I will take care of the warning in next release of the integration.
