### ISSUE TITLE
homeassistant warning - (<class 'custom_components.miele.light.MieleLight'>) does not set supported color modes

### ISSUE THREAD

**Issue by martinlindjarv** [astrandb/miele#459]
### The problem

When starting up homeassistant there is a warning in logs:
2024-03-30 11:41:19.578 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.miele.light.MieleLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at 
https://github.com/astrandb/miele/issues

Looked newer releases release notes and couldn't see this fixed.

### Version of miele integration having the issue?

v2024.1.0

### Version of Home Assistant Core having the issue?

2024.3.3

**Comment by astrandb** [comment]
Fixed in v2024.3.0 of the integration. It is written in the release note under Maintenance.

**Comment by melianor** [comment]
Hi @astrandb , 
seems like this issue made it back in. Could you please take a look?

`Entity None (<class 'custom_components.miele.light.MieleLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please create a bug report at https://github.com/astrandb/miele/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation`

**Miele Integration** 2024.11.0

**Home Assistant**
Core 2024.11.1
Supervisor 2024.11.2
Operating System 13.2
Frontend 20241106.2

**Comment by astrandb** [comment]
@melianor Thank you for reporting. 
Not exactly the same as above. It will be fixed in next release of the integration.

**Comment by melianor** [comment]
> @melianor Thank you for reporting. Not exactly the same as above. It will be fixed in next release of the integration.

Want me to open a separate issue, or are you good with it as is? :)

**Comment by astrandb** [comment]
> Want me to open a separate issue?

Yes, please do. It is easier for other users to see that it is being taken care of.
