### ISSUE TITLE
Unable to change credentials

### ISSUE THREAD

**Issue by Epimedium** [astrandb/miele#460]
### The problem

Hi,
I've tried to install the Miele integration using the wrong credentials. When I trie to reinstall, I never get the promt for the credentials. The initial credentials are saved somewhere and can't be changed anymore.
I tried removing via HACS. That doesn't work because it says that the integration is in use. The Miele integrations is not in my list of active intefrations so I can't delete it there.
Then I tried removing it by deleting the Miele folder in custom components, but that also did't solve my issue.

Does anybody have an idea how to solve this?

Best,
Erik

### Version of miele integration having the issue?

v2024.3.0

### Version of Home Assistant Core having the issue?

2024.3.0

**Comment by astrandb** [comment]
https://github.com/astrandb/miele/discussions/247
