### ISSUE TITLE
PDR508HP not shown in app

### ISSUE THREAD

**Issue by TOKL1992** [astrandb/miele#462]
### The problem

Hi, 

I have a PDR508HP (semi-professional dryer).
I can see the device in the official Miele app, but the HACS Miele Integration does not show the appliance.
If I grab the configuration file from the HomeAssistant I see that the integration has found the dryer, but it's not shown in the GUI.

Diagnostic file is attached + screenshot from the integration.

Best regards,
Tobias

[config_entry-miele-01916ef10e3bbe1af126d85fe442e062-06042024.txt](https://github.com/astrandb/miele/files/14893774/config_entry-miele-01916ef10e3bbe1af126d85fe442e062-06042024.txt)

![Screenshot_20240406_160344_Home Assistant](https://github.com/astrandb/miele/assets/66228044/3cff7fed-244b-48a0-be85-5b155cb0e178)

### Version of miele integration having the issue?

v2024.3.0

### Version of Home Assistant Core having the issue?

2024.4.1

**Comment by astrandb** [comment]
That was odd... The PDR508HP is working for other users. Please turn on Debug-Protokollierung from the screen-shot above and restart HA. Check in the log if there are any unexpected messages from the miele integration.

**Comment by TOKL1992** [comment]
[error_log-2.txt](https://github.com/astrandb/miele/files/14894046/error_log-2.txt)

I only see the message "Manually updated miele data".
Looks normal. I attached the debug logging.

**Comment by TOKL1992** [comment]
[error_log-3.txt](https://github.com/astrandb/miele/files/14894075/error_log-3.txt)

I restarted the HomeAssistant again with enabled debug logging and know I see the device and entities. Mysterious.

**Comment by TOKL1992** [comment]
After a few minutes all entities and the device are gone and not longer available.
Restarted HA a few times, without success.

**Comment by BartGysens** [comment]
Same problem here; already reported

**Comment by TOKL1992** [comment]
Also reported to Miele.
My investigation looks like, that the 3rd party API, not show the PDR508HP after one data fetch.
You can get the data once from the API and then for a unknown time not anymore.
Miele has to investigate.
The swagger UI from the Miele Homepage also delivers empty outputs in case of error.
So I look forward for a answer from Miele.

**Comment by astrandb** [comment]
@TOKL1992 Good catch! Let's hope that Miele fixes this promptly.

**Comment by BartGysens** [comment]
Anyone seen a change for this device? Miele reacted?
How can I submit also a request to Miele for change on this item; maybe a link?

**Comment by TOKL1992** [comment]
Via Mail: developer(at)miele.com
  

  

  

  
  
  
  
  
>

**Comment by BartGysens** [comment]
Answer of Miele support:

> We are sorry to inform you that the current API only supports Miele domestic appliances.
Your Miele tumble dryer is a (semi)professional appliance.

**Comment by TOKL1992** [comment]
Same answer to my mail request.
