### ISSUE TITLE
Only 1 machine is showing up

### ISSUE THREAD

**Issue by BartGysens** [astrandb/miele#476]
### The problem

I have a Washingmachine WCI860 and a Tumble dryer PDR508HP. Both were showing in Home Assistant but now the dryer is no longer showing up. Everything worked good before, no changes to the system.
In the logs I just see one machine coming in the json.

### Version of miele integration having the issue?

2024.3.0

### Version of Home Assistant Core having the issue?

2024.5.1

**Comment by astrandb** [comment]
Please get a diagnostic download from this screen. It should include everything that comes from the Miele API. If your device is not there the problem is at Miele's end.

![image](https://github.com/astrandb/miele/assets/5016010/06988d72-7159-4a20-b46f-705b4b726709)

**Comment by BartGysens** [comment]
Diagnostics:

`{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.5.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.2",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Paris",
    "os_name": "Linux",
    "os_version": "6.6.25-haos",
    "supervisor": "2024.04.4",
    "host_os": "Home Assistant OS 12.2",
    "docker_version": "25.0.5",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "spook": {
      "documentation": "https://spook.boo",
      "version": "3.0.1",
      "requirements": []
    },
    "miele": {
      "documentation": "https://github.com/astrandb/miele",
      "version": "2024.3.0",
      "requirements": [
        "flatdict==4.0.1",
        "pymiele==0.1.7"
      ]
    },
    "pyscript": {
      "documentation": "https://github.com/custom-components/pyscript",
      "version": "1.5.0",
      "requirements": [
        "croniter==1.3.8",
        "watchdog==2.3.1"
      ]
    },
    "watchman": {
      "documentation": "https://github.com/dummylabs/thewatchman",
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "proxmoxve": {
      "documentation": "https://github.com/dougiteixeira/proxmoxve",
      "version": "3.4.1",
      "requirements": [
        "proxmoxer==2.0.1"
      ]
    },
    "spook_inverse": {
      "documentation": "https://spook.boo",
      "version": "3.0.1",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "miele",
    "name": "Miele",
    "codeowners": [
      "@astrandb"
    ],
    "config_flow": true,
    "dependencies": [
      "application_credentials",
      "http"
    ],
    "documentation": "https://github.com/astrandb/miele",
    "homekit": {},
    "integration_type": "hub",
    "iot_class": "cloud_push",
    "issue_tracker": "https://github.com/astrandb/miele/issues",
    "loggers": [
      "pymiele"
    ],
    "requirements": [
      "flatdict==4.0.1",
      "pymiele==0.1.7"
    ],
    "ssdp": [],
    "version": "2024.3.0",
    "zeroconf": [
      "_mieleathome._tcp.local."
    ],
    "is_built_in": false
  },
  "data": {
    "info": {
      "auth_implementation": "miele",
      "token": {
        "access_token": "**REDACTED**",
        "refresh_token": "**REDACTED**",
        "token_type": "Bearer",
        "expires_in": 2592000,
        "expires_at": 1717617520.4309611
      }
    },
    "data": {
      "Appliance_1": {
        "ident|type|key_localized": "Soort apparaat",
        "ident|type|value_raw": 1,
        "ident|type|value_localized": "Wasautomaat",
        "ident|deviceName": "",
        "ident|protocolVersion": 4,
        "ident|deviceIdentLabel|fabNumber": "**REDACTED**",
        "ident|deviceIdentLabel|fabIndex": "54",
        "ident|deviceIdentLabel|techType": "WCI860",
        "ident|deviceIdentLabel|matNumber": "11401390",
        "ident|deviceIdentLabel|swids|0": "5801",
        "ident|deviceIdentLabel|swids|1": "20456",
        "ident|deviceIdentLabel|swids|2": "25213",
        "ident|deviceIdentLabel|swids|3": "25191",
        "ident|deviceIdentLabel|swids|4": "25446",
        "ident|deviceIdentLabel|swids|5": "25205",
        "ident|deviceIdentLabel|swids|6": "25447",
        "ident|deviceIdentLabel|swids|7": "25319",
        "ident|xkmIdentLabel|techType": "EK057",
        "ident|xkmIdentLabel|releaseVersion": "08.23",
        "state|ProgramID|value_raw": 1,
        "state|ProgramID|value_localized": "Katoen",
        "state|ProgramID|key_localized": "Programma naam",
        "state|status|value_raw": 7,
        "state|status|value_localized": "Einde",
        "state|status|key_localized": "toestand",
        "state|programType|value_raw": 1,
        "state|programType|value_localized": "Eigen programma",
        "state|programType|key_localized": "Programmatype",
        "state|programPhase|value_raw": 267,
        "state|programPhase|value_localized": "Kreukbeveiliging",
        "state|programPhase|key_localized": "Programmafase",
        "state|remainingTime|0": 0,
        "state|remainingTime|1": 0,
        "state|startTime|0": 0,
        "state|startTime|1": 0,
        "state|targetTemperature|0|value_raw": 7500,
        "state|targetTemperature|0|value_localized": 75.0,
        "state|targetTemperature|0|unit": "Celsius",
        "state|targetTemperature|1|value_raw": -32768,
        "state|targetTemperature|1|value_localized": null,
        "state|targetTemperature|1|unit": "Celsius",
        "state|targetTemperature|2|value_raw": -32768,
        "state|targetTemperature|2|value_localized": null,
        "state|targetTemperature|2|unit": "Celsius",
        "state|coreTargetTemperature|0|value_raw": -32768,
        "state|coreTargetTemperature|0|value_localized": null,
        "state|coreTargetTemperature|0|unit": "Celsius",
        "state|temperature|0|value_raw": -32768,
        "state|temperature|0|value_localized": null,
        "state|temperature|0|unit": "Celsius",
        "state|temperature|1|value_raw": -32768,
        "state|temperature|1|value_localized": null,
        "state|temperature|1|unit": "Celsius",
        "state|temperature|2|value_raw": -32768,
        "state|temperature|2|value_localized": null,
        "state|temperature|2|unit": "Celsius",
        "state|coreTemperature|0|value_raw": -32768,
        "state|coreTemperature|0|value_localized": null,
        "state|coreTemperature|0|unit": "Celsius",
        "state|signalInfo": true,
        "state|signalFailure": false,
        "state|signalDoor": false,
        "state|remoteEnable|fullRemoteControl": true,
        "state|remoteEnable|smartGrid": false,
        "state|remoteEnable|mobileStart": false,
        "state|ambientLight": null,
        "state|light": null,
        "state|elapsedTime|0": 0,
        "state|elapsedTime|1": 0,
        "state|spinningSpeed|unit": "rpm",
        "state|spinningSpeed|value_raw": 1600,
        "state|spinningSpeed|value_localized": "1600",
        "state|spinningSpeed|key_localized": "Toerental",
        "state|dryingStep|value_raw": null,
        "state|dryingStep|value_localized": "",
        "state|dryingStep|key_localized": "Droogtegraad",
        "state|ventilationStep|value_raw": null,
        "state|ventilationStep|value_localized": "",
        "state|ventilationStep|key_localized": "Ventilator niveau",
        "state|plateStep": {},
        "state|ecoFeedback|currentWaterConsumption|unit": "l",
        "state|ecoFeedback|currentWaterConsumption|value": 65.0,
        "state|ecoFeedback|currentEnergyConsumption|unit": "kWh",
        "state|ecoFeedback|currentEnergyConsumption|value": 2.0,
        "state|ecoFeedback|waterForecast": 0.3,
        "state|ecoFeedback|energyForecast": 0.8,
        "state|batteryLevel": null
      }
    },
    "actions": {
      "Appliance_1": {
        "processAction": [],
        "light": [],
        "ambientLight": [],
        "startTime": [],
        "ventilationStep": [],
        "programId": [],
        "targetTemperature": [],
        "deviceName": false,
        "powerOn": false,
        "powerOff": false,
        "colors": [],
        "modes": [],
        "runOnTime": []
      }
    },
    "id_log": []
  }
}
`

**Comment by astrandb** [comment]
There are no traces of a dryer. You should report this to Miele.

**Comment by BartGysens** [comment]
Ok; thank you for the reply.
Closing this issue and referring to this issue => https://github.com/astrandb/miele/issues/462

**Comment by BartGysens** [comment]
Thank you for the great work!
