### ISSUE TITLE
Force to reauthenticate every 4 days

### ISSUE THREAD

**Issue by Phyxsius7** [astrandb/miele#488]
### The problem

I have installed this integration fresh via HACS. Had no issues during.
Each 4 days, api connection is not possible and in HA I see a notification that I need to reauthenticate.

### Version of miele integration having the issue?

v2024.5.0

### Version of Home Assistant Core having the issue?

2024.5.5

### Anything in the logs that might be useful for us?

```txt
This entity ('configurator.miele_home') does not have a unique ID, therefore its settings cannot be managed from the UI. See the documentation for more detail.



Logger: homeassistant.helpers.frame
Source: helpers/frame.py:190
First occurred: 9:39:36 PM (3 occurrences)
Last logged: 9:40:41 PM

Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'miele' accesses hass.components.configurator. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from configurator directly at custom_components/miele/__init__.py, line 363: configurator = hass.components.configurator, please create a bug report at https://github.com/HomeAssistant-Mods/home-assistant-miele/issues
Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
```

**Comment by astrandb** [comment]
You are not using the integration in this repo. Please report the issue to `https://github.com/HomeAssistant-Mods/home-assistant-miele/issues´.
Or uninstall your installed integration and install this one instead. 😉

**Comment by Phyxsius7** [comment]
Hi,
I am surprised after reading your reply.
I opened a issues here because the link from HA directed me, see attachment.

https://github.com/astrandb/miele/assets/26312344/6a6704e8-72b2-4133-b614-d11e263b7ca0

This made be believe that I am on the correct GitHub page.

**Comment by astrandb** [comment]
I an also a bit surprised. Look at the second log line above - scroll to the far right. The log message refers to another integration. The code line in the reference does not exist in this repo.

So there must be a mix of two integrations in your installation.

You need to start over with a clean sheet. 

1. Uninstall the miele integration from HA.
2. Remove the integration from HACS.
3. Remove any custom repository for Miele in HACS
4. Restart HA

6. Download the Miele integration via the default library in HACS i.e. this repo.
7. Restart HA
8. Install the Miele Integration in HA, Follow the prompts for credentials etc

**Comment by astrandb** [comment]
Stale issue - closing
