### ISSUE TITLE
Add Language: Luxembourgish

### ISSUE THREAD

**Issue by maxhamilius** [astrandb/miele#492]
### Feature request

Please add Luxembourgish language. I am willing to contribute to the translations on Lokalise.

### What version of the integration are you using?

 v2024.5.0

**Comment by astrandb** [comment]
Luxembourgish added to Lokalise. The translation will be included in next release of the integration

**Comment by maxhamilius** [comment]
The language has still not appeared on Lokalise.

**Comment by astrandb** [comment]
@maxhamilius Luxembourgish was not enabled on your profile, probably because it was not available when your profile was created. Now it should be OK.
