### ISSUE TITLE
Changing password not possible?

### ISSUE THREAD

**Issue by Supergrobi4711** [astrandb/miele#497]
### The problem

Hi everyone. I am a total newbie with Home Assistant. So please excuse if my question is unnecessary.
I have an account for the Miele App, and it works with my dryer.
After having installed the Miele integration, I made a typo when entering the Miele login data.
Thus the connection between Home Assistant and Miele is not working. Reply from Miele website: "invalid_client: Client credentials are not valid"
Wanting to change the password for my login in the integration, it seems not possiple to do so.
I did remove and re-install the integration several times (also re-starting Home Assistant after the removal), but the wrong login data keep re-inserting themselves after the re-installation. No chance to re-enter them again.
The only solutions I can think of is 1. creating a new user with a different email adress for the Miele App, or 2. to delete set up a fresh installation of Home Assistant. 
It would be easier though if I could just correct the error within the integration.
Any ideas? 
Thanks in advance.

### Version of miele integration having the issue?

2024.5.0 

### Version of Home Assistant Core having the issue?

2024.6.4

**Comment by ohaak2** [comment]
Same issue for me. Had to change the credentials on Miele side and then just wanted to re authenticate the integration using the new credentials. However the integration seems to re inject the old credentials and skips the "enter credentials" dialog. Result is then as described above. 

Tried wiping the integration and reinstalling. Tried using in private browser session but to no avail. My impression is that these settings are somehow stored on Homeassistant side (apart from the integration ) and need to be deleted there first. 

Anyways - I think a possibility to actually reauthenticate with new credentials in the integration settings would be a nice option.

**Comment by astrandb** [comment]
There is no elegant way to changeactive  client-id and/or client-secret in HA. But you can delete the currently stored credentials, please see here https://github.com/astrandb/miele/discussions/247 . 
The username and password for your Miele account are never stored in HA, that is one of the fundamental ideas in OAuth2 authentication.

**Comment by Supergrobi4711** [comment]
Thank you both. Indeed the solution was that the login credentials for Miele are found on the Settings->Integrations site.
 Secondly I found out that I need not only to have the login data from my Miele App. But first I needed to register here: https://www.miele.com/f/com/en/register_api.aspx
Then I received an Email from Miele including the Client ID and Client Secret, which are totally different to the Miele App credendials. Together with both sets of identification data, I finally got it to work.

**Comment by Supergrobi4711** [comment]
Closed.

**Comment by ohaak2** [comment]
> There is no elegant way to change active client-id and/or client-secret in HA. But you can delete the currently stored credentials, please see here #247 . The username and password for your Miele account are never stored in HA, that is one of the fundamental ideas in OAuth2 authentication.

Thanks! That was exactly the information I was missing!
