### ISSUE TITLE
THE INTEGRATION DOES NOT APPEAR

### ISSUE THREAD

**Issue by picardi21** [astrandb/miele#508]
### The problem

Ciao io ho eseguito correttamente l'installazione registrandomi anche sul sito da te segnalatO, ma poi non mi esce l'integrazione in "dispositivi e servizi", ho provato anche a cancellare la cache. Suggerimenti per risolvere il problema?

### Version of miele integration having the issue?

v2024.5.0

### Version of Home Assistant Core having the issue?

2024.7.3

**Comment by mundschenk-at** [comment]
> Suggerimenti per risolvere il problema?

You might start by writing in English.

**Comment by picardi21** [comment]
Hi, I carried out the installation correctly by registering on the site you mentioned, but then the integration in "devices and services" doesn't work, I also tried to clear the cache. Suggestions to fix the problem?

**Comment by picardi21** [comment]
Once the entire installation procedure is done, I am redirected to the Miele website, I enter the username and password and then restart HA. The problem is that in the "devices and services" section no Miele integration appears.

**Comment by mundschenk-at** [comment]
Please describe step by step what you have been doing, starting from the beginning. Are you using HACS?

**Comment by picardi21** [comment]
I install the integration from HACS, go to "devices and services" and search for Miele. After clicking on it I am redirected to the Miele Developer site, I enter username and password and again I am redirected to HA. I restart HA. I tried locally and remotely.

**Comment by mundschenk-at** [comment]
Why did you restart HA after logging in to the Miele website? I thought you were talking about the HACS installation when I suggested the restart (adding an integration is not "installation" as I use the term).

**Comment by picardi21** [comment]
I attach the video of the procedure
https://github.com/user-attachments/assets/9cea9832-3774-40fa-9c22-84a65880c22c

**Comment by picardi21** [comment]
<img width="559" alt="Screenshot 2024-09-16 alle 22 24 42" src="https://github.com/user-attachments/assets/65f9d843-ed15-4f16-9935-6d8548e411b0">
Hi, do you have a solution to suggest? I can't see your integration

**Comment by Hubi-Swiss** [comment]
Same here, it shows only the update entity

**Comment by astrandb** [comment]
The "Miele update" is generated by HACS - not by this integration. 

If your device belongs to semi-professional or professional series there will probably be problems due to incomplete and unreliable support in the Miele API. Make sure that your device is consumer grade. Beta version 2024.9.0b1 of the integration will log a message if an affected model is discovered in your account.

There is probably something corrupt in the installation of the integration in your instance. It is not trivial to find the root cause so I suggest that you remove all traces of the integration and start over.
1. Restart Home Assistant
2. Goto HACS and remove the Miele integration. - Open the three-dot-menu at the Miele entry and select Remove.
3. Restart Home Assistant 
4. Goto HACS - Enter Miele in the search bar, select Miele integration and click download.
5. Restart Home Assistant
6. If there is a reasonably modern Miele device on your LAN it should be discovered by HA within a few minutes if your LAN allows broadcasts. If the device is not auto-discovered you can add the integration manually by following instructions below.
7. Goto Settings->Devices&services, Click Add Integration and select Miele
8. Follow the instructions to setup the integration.
9. You can see the expected flow here https://github.com/astrandb/miele/discussions/366 . Please report  which step that fails.

**Comment by Hubi-Swiss** [comment]
Dear Ake

Thank you for your quick response. I am a rookie on HA. I will be back at home next week and try it out.
I do not know which Series my devices are, but they all appear in the Mile App.

KF 2981 VI
H7840BPX
DGC7845X
G7595
CVA7845
ESW7010 D


Thank you for your support

Best regards

Hubertus Willeke

**Comment by Hubi-Swiss** [comment]
> The "Miele update" is generated by HACS - not by this integration.
> 
> If your device belongs to semi-professional or professional series there will probably be problems due to incomplete and unreliable support in the Miele API. Make sure that your device is consumer grade. Beta version 2024.9.0b1 of the integration will log a message if an affected model is discovered in your account.
> 
> There is probably something corrupt in the installation of the integration in your instance. It is not trivial to find the root cause so I suggest that you remove all traces of the integration and start over.
> 
> 1. Restart Home Assistant
> 2. Goto HACS and remove the Miele integration. - Open the three-dot-menu at the Miele entry and select Remove.
> 3. Remove application credentials. Goto Settings->Devices&services, open the three dot menu in upper right corner and goto Application credentials.
> 4. Restart Home Assistant
> 5. Goto HACS - Enter Miele in the search bar, select Miele integration and click download.
> 6. Restart Home Assistant
> 7. If there is a reasonably modern Miele device on your LAN it should be discovered by HA within a few minutes if your LAN allows broadcasts. If the device is not auto-discovered you can add the integration manually by following instructions below.
> 8. Goto Settings->Devices&services, Click Add Integration and select Miele
> 9. Follow the instructions to setup the integration.
> 10. You can see the expected flow here [How to set up the Miele integration #366](https://github.com/astrandb/miele/discussions/366) . Please report  which step that fails.

Hi Ake
failing in step 3. I am not able to delete the credentials.
![Bildschirmfoto 2024-10-01 um 15 24 24](https://github.com/user-attachments/assets/428c4c43-6b2d-4e8d-9839-00e603ba5fac)

**Comment by astrandb** [comment]
The integration has gone into a dead-lock state for a couple of users. I dont understand why/how this happened and is a pretty advanced process to recover. There are more than 8000 users not having this problem, though.

Please browse to [your_HA]/config/integrations/integration/miele and make a screen dump.

Would it be possible to let me access your HA remotely? Please contact me on ake@strandberg.eu and I can explain more.

**Comment by Hubi-Swiss** [comment]
Hi Ake
thanks for you quick response. Attached the requested screenshot. I will in addition contact you via mail to give you remote access to my HA.

Best

Hubertus
![Bildschirmfoto 2024-10-01 um 16 30 38](https://github.com/user-attachments/assets/b53ba552-874a-4c85-9f4c-0c4cb2127a5b)

**Comment by ciato** [comment]
I have the exact same issue as @picardi21. Integration does not show up but I cannot delete the credentials. I also get the notification that credentials in use may not be deleted.  
It is different than @Hubi-Swiss though. I do not have a Miele integration visible in the configured integrations list. However, the update entity and pre-release entity are available.

**Comment by Hubi-Swiss** [comment]
Hi Ake

thank you so much you made my day. It works. Again thank you for your effort.
<img width="621" alt="Screenshot 2024-10-03 at 07 39 09" src="https://github.com/user-attachments/assets/a79a2e43-ee79-49c6-85be-f6f4fec26451">

**Comment by ciato** [comment]
@Hubi-Swiss Could you please describe the steps you took to solve your issue?

**Comment by astrandb** [comment]
There is probably a stale config entry in HA. It needs manual intervention to remove. If the integration was properly installed the delete procedure would clean out the config entry but for unclear reasons it is left behind.

Use a terminal to access the linux prompt (install Terminal&SSH add-on).
- Edit (eg with nano) /config/.storage/core.config_entries
- Remove the miele entry - make sure that you don't damage the json structure. Save a backup of the file before changing anything.
- Save the edited file
- Restart HA 
- Add the Miele integration  (Goto Settings->Devices & services). With a little luck the Miele integration is auto-discovered, else you have to add it manually.

**Comment by astrandb** [comment]
Try to remove all traces of the integration.
```rm -r /config/custom_components/miele```
Restart HA and download the Miele integration with HACS and restart HA again.

**Comment by ciato** [comment]
Thank you for your quick response. I get the following response: No such file or directory. Seems like the directory is already completely removed after uninstalling the integration from HACS.

**Comment by astrandb** [comment]
If the directory is empty/non-existing everything should be good. I dont really understand why/how the config entry is recreated if there is no miele code left in the system. You could try to rename miele to miele2 in the config entry - note that there are a couple of occurrances.
When HA finds a miele entry in the config entry the setup code will enter wrong path. I cannot really find out why this entry is left behind since I cannot reproduce the situation in my systems.

**Comment by ciato** [comment]
I tried editing the file in a different way and it worked. The file did not save in my first attempts. Now it did and I was able to reconfigure the integration. Sorry for the inconvenience. Thank you for your support and the effort you put in making this integration!
