### ISSUE TITLE
No Miele Integration anymore

### ISSUE THREAD

**Issue by erdna** [astrandb/miele#514]
### The problem

There is noch Miele Integration any more in Home Assistant. See Screenshots
![Screenshot_20240731-170239](https://github.com/user-attachments/assets/9f79579b-0144-4214-99a8-58b61186485e)
![Screenshot_20240731-170223](https://github.com/user-attachments/assets/2c94e36d-c5ea-41d6-98f9-160719714c20)
![Screenshot_20240731-170153](https://github.com/user-attachments/assets/b6534827-054d-4e68-a3f6-1764badc09f6)

### Version of miele integration having the issue?

?

### Version of Home Assistant Core having the issue?

2024.7.4

**Comment by CFenner** [comment]
This is an integration that is installed via HACS, please check if it installed in there.


<img width="422" alt="Bildschirmfoto 2024-08-06 um 13 16 48" src="https://github.com/user-attachments/assets/3b2e496e-d825-4f14-8017-54a4ea35c509">

**Comment by astrandb** [comment]
Stale issue - closing
