### ISSUE TITLE
Superfrost as hvac mode / preset 

### ISSUE THREAD

**Issue by CFenner** [astrandb/miele#517]
### Feature request

It would be nice to have the super frost function included into the climate entity.

We could request an architecture change to get a new `HVACMode` or use the `PRESET_BOOST` for that.

https://github.com/home-assistant/core/blob/31fd4efa368f5f05129c1493debcff1b5fb236c5/homeassistant/components/climate/const.py#L60-L61

### What version of the integration are you using?

latest

**Comment by astrandb** [comment]
> We could request an architecture change to get a new `HVACMode` or use the `PRESET_BOOST` for that.

I am pretty sure that an architecture change will not be accepted for a single custom component, But there might be other ways. I will take a look...

**Comment by CFenner** [comment]
Also my freezer has some other modes that would be nice to have as presets: 

![IMG_4D2AEA4B17FA-1](https://github.com/user-attachments/assets/dc350802-bc38-4105-812e-ab5ceaaf2a59)

But I did not see anything that looks related to me in the API. Wonder if that could be controlled somehow.

**Comment by astrandb** [comment]
These extra controls are not available in the public API. This also applies to ice-maker on/off. 
Miele has another internal API that they use for their app. The development of public API is a low priority project - unfortunately.
