### ISSUE TITLE
2024.8.1 Update reconfigure ends in HTTP 404

### ISSUE THREAD

**Issue by UlrichThiess** [astrandb/miele#531]
### The problem

After upgrade the Miele Integration to 2024.8.1 it wan't to reauthenticate. But the link seems to be wrong.
{"code":404,"message":"HTTP 404 Not Found"}

### Version of miele integration having the issue?

miele-2024.8.1

### Version of Home Assistant Core having the issue?

core-2024.8.0

**Comment by nagyrobi** [comment]
Same here, `{"code":404,"message":"HTTP 404 Not Found"}`.

**Comment by cvc90** [comment]
Same error, after updating to the new version of Miele in Home Assistant 2024.8

**Comment by andrewmooreio** [comment]
FYI I think Home Assistant 2024.8 may be a red herring.

I'm running Home Assistant 2024.7.4 and Miele integration version v2024.5.0 and hitting the same issue after a HA restart.

**Comment by andrewoe** [comment]
same here after updating the Miele integration.... They a excellent in building machines, but like a lot of manufacturer, the are really bad in developing software....

**Comment by kickouille** [comment]
Exactly @andrewmooreio, I am still running 2024.7.4 and I have the same issue, I restarted earlier today, 2024.8 release is a coincidence, because it also requires a restart.

**Comment by aselling** [comment]
Miele API service is down. Even their own app doesn't work

**Comment by dbhorst** [comment]
If you manually authorize in their Swagger-UI, you get a 404 too.
https://www.miele.com/developer/swagger-ui/index.html

**Comment by purewhitedesign** [comment]
Same here.

**Comment by UlrichThiess** [comment]
Ok, so i see what's going on tomorrow. Maybe they have Miele-Patch-Day? :-)

**Comment by nagyrobi** [comment]
> the are really bad in developing software....

Maybe their sever was hacked...

**Comment by nagyrobi** [comment]
But also, a thing to consider, implement checks for such server side malfunctions in the component to just set the entities as unavailable...

**Comment by cvc90** [comment]
It looks like the API is back up and running again in Home Assistant 😄

**Comment by nagyrobi** [comment]
And it doesn't need any re-authentication. A simple HA restart fixes it.

**Comment by UlrichThiess** [comment]
Yesss.
