### ISSUE TITLE
Reauthentication needed/failed 2024.8.1

### ISSUE THREAD

**Issue by andreasbuff** [astrandb/miele#532]
### The problem

I am getting an error: "Action need" -> After this "reautentication" on Website is failing? Pls help
UPDATE: I started Backup-HA-Instance with Mile Integration: 2024.5.0.  -> Same Problem here, as with Mile Integration: 2024.8.0 . **Hence looks like Miele API is down...**, or Mile has changed API?

### Version of miele integration having the issue?

Mile

### Version of Home Assistant Core having the issue?

CORE 2024.8.0 and HAOS 13.0.rc2

### Anything in the logs that might be useful for us?

```txt
Error Message: "Authentication expired".. -> "HTTP status 401: Retry 2"  
After moving to Web-Site: "{"code":404,"message":"HTTP 404 Not Found"}"
```

**Comment by abard35** [comment]
Same problem/issue

Core 2024.8.0
Operating System 12.4

{"code":404,"message":"HTTP 404 Not Found"}

**Comment by cvc90** [comment]
Same error, after updating to the new version of Miele in Home Assistant 2024.8

**Comment by Bloodpack** [comment]
same here with

Miele Integration Version 2024.8.1

Core  2024.8.0
Supervisor  2024.08.0
Operating  System 12.4
Frontend  20240806.1

{"code":404,"message":"HTTP 404 Not Found"}

**Comment by Luke7001801** [comment]
Same problem/issue

Core 2024.8.0
Operating System 12.4

{"code":404,"message":"HTTP 404 Not Found"}

**Comment by vangilz** [comment]
Same issue here. I don't believe it's related to the version.

**Comment by itrankolov** [comment]
Seems to be a problem on Miele servers. I've tried to re-register and it fails with "Your registration request has failed. Please try again later".

**Comment by gschmidl** [comment]
Going to the endpoint URL manually also yields a 404. I double-checked the Miele developer documentation's swagger, it has not changed.

**Comment by aselling** [comment]
Miele API service is down. Even their own app doesn't work

**Comment by Luke7001801** [comment]
That's not correct. I can use the App without issues.

**Comment by Bloodpack** [comment]
> Miele API service is down. Even their own app doesn't work

For me here in Germany the App works

**Comment by MaxiKingXXL** [comment]
Same problem/issue

Core 2024.8.0

**Comment by timobert** [comment]
Same problem.  My Miele app is working fine but the integration is asking me to re-authenticate.  Connection was working fine until it went down at 10:42 AM EDT.

**Comment by Eniste1** [comment]
Unfortunately same issue here...

**Comment by KoalaWerewolf** [comment]
I have the same issue on 2024.7.3. Thought I'd add that info since most comments with this issue are on 2024.8.

**Comment by cvc90** [comment]
It looks like the API is back up and running again in Home Assistant 😄

**Comment by holger-tangermann** [comment]
> It looks like the API is back up and running again in Home Assistant 😄

Yes. Works again.

**Comment by andreasbuff** [comment]
@holger-tangermann: Thanks. API is back and Integration is working again

**Comment by Bloodpack** [comment]
Yep, works again
