### ISSUE TITLE
Missing coffee machine status: 147

### ISSUE THREAD

**Issue by IngmarStein** [astrandb/miele#551]
### The problem

I noticed that the status entity of my coffee maker shows the raw number when it's doing the automatic nightly cleaning:

![Bildschirmfoto 2024-09-17 um 21 14 23](https://github.com/user-attachments/assets/5d0ddadf-0fa4-4df8-b7c3-39139ccb0753)

It should probably be added [here](https://github.com/astrandb/miele/blob/de141ad3051758235ae9136a9e76b2fcf249a21b/custom_components/miele/const.py#L134C1-L135C1) and be localized properly. Are there some official strings to use?

### Version of miele integration having the issue?

2024.8.1

### Version of Home Assistant Core having the issue?

2024.9.2

**Comment by astrandb** [comment]
Thank you for reporting. 
Do you know the english and/or german terms for this status. Is it shown on the display or are there any clues in the manual?

**Comment by IngmarStein** [comment]
I rarely look at the coffee machine at 2 am, so I don't know what exactly is shown, but it should be something like "automatic cleaning" / "Automatisches Pflegeprogramm" according to the manual.

**Comment by astrandb** [comment]
Just released a beta version where this issue is fixed. Lokalization for English, German and Swedish is added and remaining languages will be updated in Lokalise by the community later on.
@IngmarStein you can test the beta by doing a re-download of the integration in HACS and selecting v2024.9.0b1 and restarting HA.

**Comment by IngmarStein** [comment]
Thanks! I've installed the beta will will report back tomorrow after the next cleaning cycle.

**Comment by IngmarStein** [comment]
Works great, thanks!

![Bildschirmfoto 2024-09-19 um 06 53 48](https://github.com/user-attachments/assets/e18cb986-a215-404f-9846-4202b6f1839d)
