### ISSUE TITLE
Can't set up devices after installation. "Config flow could not be loaded: {"message":"Invalid handler specified"}" 

### ISSUE THREAD

**Issue by DorjeDorf** [astrandb/miele#568]
### The problem

I am now in the process of performing a clean installation of HA and wanted to get this amazing plugin working. 
However, no matter the version of the integration (I went back as far back as 0.1.21) - I get the exact same error. 

Config flow could not be loaded: {"message":"Invalid handler specified"}

The one message I see in the logs is this:

`Error occurred loading flow for integration miele: No module named 'flatdict'
`

How can I help you gather more logs to troubleshoot this issue? I see another person had this issue a month ago in another topic, but there was seemingly no reaction to it.

https://github.com/astrandb/miele/discussions/366#discussioncomment-10712120

Would be great if we could get this fixed. 

### Version of miele integration having the issue?

All versions since 0.1.21 - including recent RCs

### Version of Home Assistant Core having the issue?

2024.10.3

**Comment by astrandb** [comment]
It is not recommended to install old versions of the integration with current versions of HA. It will not work and can lead to unexpected behavior.
The message that flatdict module is missing is a sign that the whole installatoin is corrupt. 
The best way to recover would be to restore a working backup of HA dated just before you started to install this integration.
If that is not possible the recovery procedure depends on how you have set up your HA.
What environment are you running HA in? HAOS?, core ??
How did you install the integration? with HACS?

**Comment by DorjeDorf** [comment]
Thanks for answering. 

I don't have backups, since it's a fresh installation (2 days old) and I'm slowly adding components to it. 
I used older versions to make sure that an earlier version wouldn't fix the issue (as in something introduced in the most recent one - since I had this integration working perfectly on my old setup that had other issues). 

I am running core as a docker image standalone without HAOS (dumping HAOS was one of the main reasons for this move). 
The integration was installed with HACS. 

I logged into the shell of the docker image and tried to install flatdict==4.0.1 manually. It gets installed, but is dumped after I restart the docker instance - and does not help with the integration itself seeing the library present.

**Comment by astrandb** [comment]
The manually installed flatdict lib is probably installed somewhere where it is unreachable by the runtime...
You should try to remove all traces of the miele installation and start over.
1. Uninstall it with HACS
2. Restart HA
3. Open a linux prompt and cd to your config directory
4. Remove miele integration (`rm -r ./custom_components/miele`)
5. Restart HA, make sure that there is nothing suspicious in the HA log
6. Remove credentials (goto Settings/Devices and services -> 3-dot menu)
7. Download the miele integration (v2024.8.1) with HACS
8. Restart HA
9. Check the logs
10. If you are lucky your Miele appliance will be autodiscovered and you can click Configure to enter setup. Otherwise add the integration manually in Settings->Devices and services.

It this procedure does not work, there might be remnants of the previous miele integration in other places.

**Comment by DorjeDorf** [comment]
I went a step further. I trashed the whole setup and remade it from scratch. 

It did not help. 

On a clean HA with just HACS installed, your integration loads up perfectly. I restart HA and then try to add it in devices - it thinks a bit then throws the error about flatdict. 

Logs have a single entry. 

`Logger: homeassistant.config_entries
Source: config_entries.py:2945
First occurred: 6:23:08 PM (1 occurrences)
Last logged: 6:23:08 PM

Error occurred loading flow for integration miele: No module named 'flatdict'`

**Comment by astrandb** [comment]
The library should be installed by HA without any manual intervention. I have no clue where the problem comes from. Is flatdict incompatible with your python version or anything else in your setup?

**Comment by DorjeDorf** [comment]
Shouldn't be. As I said - clean install. Or rather - clean multiple installs :D 

Either way, I just discovered another problem with a dockerized HA - much less convenient backups and restores. 
I'll be reluctantly going back to bare metal, or push myself to try proxmox again... 

Closing the ticket. Thanks for the support thus far :D
