### ISSUE TITLE
Light and fan on DA 2628 cooker hood show 'on' when actually off

### ISSUE THREAD

**Issue by stuartperry** [astrandb/miele#76]
### The problem

Things that perform as expected:

When the light and fan are both actually off then [sensor.cooker_hood_status] and [switch.cooker_hood_power_on] both show 'off', all good.

When light is actually on then [sensor.cooker_hood_status] switches to 'running', while [switch.cooker_hood_power_on] remains 'off', that's good.

When the fan is actually on then [sensor.cooker_hood_status] switches to 'running', and [switch.cooker_hood_power_on] goes to 'on', that's also good.

And when the fan is on then Power level '1/2/3/Booster' correspond to 'preset_modes' 1/2/3/4 in HA, and update instantly, so that's awesome. When when the fan is off then 'preset_mode' displays as 0, all good.

Things that don't perform as expected:

When the fan is actually off then 'state' in HA is 'on'.  And it goes to 'off' in HA when it's actually on and running.

And ditto for the light.

### Version of miele integration having the issue?

0.0.18

### Version of Home Assistant Core having the issue?

2022.3.7

### Additional information

[miele-6b93f5e2ccf41c20e29c4d8dd9b9b893-Cooker hood-3d20a17817d39a83c8c71766e48c94d0.json.txt](https://github.com/astrandb/miele/files/8365836/miele-6b93f5e2ccf41c20e29c4d8dd9b9b893-Cooker.hood-3d20a17817d39a83c8c71766e48c94d0.json.txt)

![Screenshot 2022-03-28 at 21 05 05](https://user-images.githubusercontent.com/31155769/160478113-c596eb7a-4f37-4f5e-a622-d4e957a983c2.png)

**Comment by astrandb** [comment]
Thank you for your detailed description. I have no cooker hood from Miele so I cannot test myself.
A quick look in the code shows that I forgot to update the `is_on` property for the fan.  It is always returning True. My mistake. 
 
But there are at Ieast two ways to define the value for `is_on`:
1 False when preset_mode is 0 and True otherwise.
or 
2 Folllow `status` off/running

Probably 1 is the best alternative

Regarding the light:
It is not clear to me why the `is_on` property is inverted. I believe I followed the documentation. Can you please take a diagnostic download with the light on and one with the light off.
I can also see that the API reports both light and ambientLight for your hood. Are there two different lights that can be controlled individually?

**Comment by stuartperry** [comment]
Thanks for quick reply. Please find below some files for the four potential state-combos of light (there is only one) and fan (set to off, or speed 2). Am I right that it's using 'ambientLight' as the fan-speed?

[LightsOffFanOff.json.txt](https://github.com/astrandb/miele/files/8368595/LightsOffFanOff.json.txt)
[LightsOffFanOn.json.txt](https://github.com/astrandb/miele/files/8368596/LightsOffFanOn.json.txt)
[LightsOnFanOff.json.txt](https://github.com/astrandb/miele/files/8368597/LightsOnFanOff.json.txt)
[LightsOnFanOn.json.txt](https://github.com/astrandb/miele/files/8368598/LightsOnFanOn.json.txt)

**Comment by astrandb** [comment]
Thank you. I spotted the problems now. I will fix the bugs later this week.
No, `ambientLight` is probably not used att all in this model of hood. `ventilationStep` is used to set the fan speed.

**Comment by stuartperry** [comment]
Brilliant. thank you for doing it so quickly!

One small remaining thing ... when HA is rebooted then the fan 'preset_mode' comes in as 'null', rather than 0, and that renders the State of the fan as on.  Please could you make 'null' also mean 'off'?

All working brilliantly though, I have an automation to switch the cooker hood light on with my other kitchen lights, and another that switches the light+fan off when I turn the main kitchen lights off, and they work beautifully now.


After a HA restart:
![AfterRestart_pic](https://user-images.githubusercontent.com/31155769/160918877-3b809c77-85d1-462f-a3d0-969320ca48e5.png)
[AfterRestart.json.txt](https://github.com/astrandb/miele/files/8383675/AfterRestart.json.txt)



After cycling the fan on then off again:
![AfterCycling_pic](https://user-images.githubusercontent.com/31155769/160918914-f884741c-b7f5-4960-9d0f-ab1e02da49f4.png)
[AfterCycling.json.txt](https://github.com/astrandb/miele/files/8383676/AfterCycling.json.txt)

**Comment by astrandb** [comment]
@stuartperry beta-3 should take care of null and 0

**Comment by stuartperry** [comment]
That seems to have broken everything unfortunately, neither the light or fan work now, the status doesn't change when they're on, it looks like this regardlesss:

![Screenshot 2022-03-31 at 07 00 57](https://user-images.githubusercontent.com/31155769/160987006-ecef5e69-a2ae-4363-8f0e-7afaf5aa95f8.png)

[EverythingOff.json.txt](https://github.com/astrandb/miele/files/8386398/EverythingOff.json.txt)
[EverythingOn.json.txt](https://github.com/astrandb/miele/files/8386400/EverythingOn.json.txt)

**Comment by stuartperry** [comment]
Sorry, I'd updated using the HACS app on my phone, and even though I selected b3 on there it seems to have installed b2!

Installed b3 using Safari on my desktop now, and it all works perfectly!! Thanks so much!

**Comment by astrandb** [comment]
Thank you @stuartperry with squashing these bugs.
