### ISSUE TITLE
Fan entity (from cooker hood DA 2628) reports Presets as separate entities in HomeKit ... possible to make it one entity?

### ISSUE THREAD

**Issue by stuartperry** [astrandb/miele#80]
### Feature request

I'm using the HomeKit integration in HA to expose various entities, one of which is the Fan.

It exposes it as five separate entities, one for on/off, and one for each of the four preset-speeds.

It actually works pretty well... if it's off and you click the icon at the bottom, and then click one of the Preset sliders to on, then the on/off toggles appropriately. Likewise if it's on, and you click the 'Fan on' icon at the very top, then it quickly shuts off, and all the entities go to off.

Feature request would be to turn it into a single-entity 'analogue slider', a bit like a light-dimmer, where 0% is off, 25% is preset 1... 100% is preset 4.

### What version of the integration are you using?

0.0.19

### Additional information

Summary screenshot with everything off, all 5 entities are by default aggregated into one icon:

![Screenshot 2022-03-31 at 22 11 25](https://user-images.githubusercontent.com/31155769/161150766-953ca2ac-29b6-4808-adbf-2604efc122f6.png)

When you click the button you get this scrollable window:
![Screenshot 2022-03-31 at 22 25 34](https://user-images.githubusercontent.com/31155769/161151915-06ed977f-593e-4048-9d81-6e2135f62dd4.png)
![Screenshot 2022-03-31 at 22 26 33](https://user-images.githubusercontent.com/31155769/161152059-98be93af-d350-4f39-9def-8f7c8ba6097b.png)

Detailed view (after clicking 'settings' inside that icon) of the entities inside:

![Screenshot 2022-03-31 at 22 11 59](https://user-images.githubusercontent.com/31155769/161150775-9c13a87a-fd35-4cce-a9fb-a60dab0a60c2.png)

When the slider is switched on for Preset 2

![Screenshot 2022-03-31 at 22 19 27](https://user-images.githubusercontent.com/31155769/161151098-4a80e6d8-79a0-43f7-a5f9-484189945354.png)

![Screenshot 2022-03-31 at 22 12 50](https://user-images.githubusercontent.com/31155769/161150783-e393b3c9-1d6a-4f35-b8fd-03bf3b45a60f.png)

HA Developer screen screenshot:
![Screenshot 2022-03-31 at 22 18 21](https://user-images.githubusercontent.com/31155769/161150992-d8214a8f-3ee8-45b8-b8d9-4e790abfce76.png)

HomeKit Diagnostics:
Fan off
[HomeKit_FanOff.json.txt](https://github.com/astrandb/miele/files/8393194/HomeKit_FanOff.json.txt)

Fan set to 2:
[HomeKit_FanOn.json.txt](https://github.com/astrandb/miele/files/8393195/HomeKit_FanOn.json.txt)

**Comment by astrandb** [comment]
Your feature request is definitely logical, but here are a few things to consider though.
- The Miele API defines a number of discrete `ventilationSteps`. Your hub model accepts [1, 2, 3, 4] but it does not accept 0.
- Turning on and off is handled by the `powerOn` / `powerOff` action command
- The API reports ventilationStep = 0 when power is off

HA has built-in support for a slider control for setting the speed of the fan from 0-100% so that is no big problem. We just have to map the discrete steps to percentages and vice versa.
Perhaps the most user-friendly approach is to use the slider mode and sort out what API commands to send for the specific settings. And then drop the `Preset Mode` selector. And the hope that HomeKit bridge behaves properly.

I'll wait for a rainy day and look into this...

**Comment by stuartperry** [comment]
Sounds good, thanks a lot! It's all super-useable as it is, this "feature enhancement" would ultimately be more about prettying-up the HomeKit interface than adding functionality. So no rush for sure.

Thanks so much for all your great work on this project!

**Comment by astrandb** [comment]
Short answer is yes. I dont know the internals but if the backend reports the state in discrete steps the frontend will behave accordingly.

**Comment by astrandb** [comment]
@stuartperry I have pushed a new branch `FanPercentage` that changes and simplifies the fan control. It would make things quicker for me if you can test it by just downloading fan.py from that branch to your custom_components/miele/ and restarting HA. If you have trouble with doing that I can release a new beta but that will perhaps confuse other users with beta downloads enabled.

**Comment by stuartperry** [comment]
Sorry for long delay, for some reason I totally missed the notification of a new message.

But in good news it works super-perfectly! One single entity in HomeKit, and also it seems to auto-round itself to the nearest 25% when dragging the slider.

Looking good in HA too obviously!

Thanks so much for this!

![Screenshot 2022-04-11 at 20 23 28](https://user-images.githubusercontent.com/31155769/162814377-e4a0d4ee-587d-4b8d-9688-15a2accb933e.png)

![Screenshot 2022-04-11 at 20 23 09](https://user-images.githubusercontent.com/31155769/162814393-fa3be462-9b77-44d7-a1c2-fe54632b0ba0.png)
