### ISSUE TITLE
Washing machine miele.set_program

### ISSUE THREAD

**Issue by koburg** [astrandb/miele#88]
### The problem

i have read the bugs already about washing machine but keep get 400 bad request when I try the miele.set_program.

I have set the washing machine to mobile start which means im able to control the machine from the mobile app and start/stop choose programs etc.

`service: miele.set_program
target:
  device_id: eb43e0b5295bc0dc0c430ebce37e4136
data:
  programId: 1`

i have tried alle program id's I can see in the swagger no one work.

### Version of miele integration having the issue?

0.0.20

### Version of Home Assistant Core having the issue?

2022.4.5

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/miele/services.py:202 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 16.14.37 (1 occurrences) 
Last logged: 16.14.37

[140192461466688] Service set_program: 400 Bad Request
Traceback (most recent call last):
  File "/config/custom_components/miele/services.py", line 200, in set_program
    await _api.set_program(serno, data)
  File "/usr/local/lib/python3.9/site-packages/pymiele/pymiele.py", line 108, in set_program
    res.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.mcs3.miele.com/v1/devices/000150012439/programs')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 282, in service_handler
    await script_entity.async_turn_on(
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 386, in async_turn_on
    await coro
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 412, in _async_run
    return await self.script.async_run(script_vars, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1275, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 379, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 582, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/miele/services.py", line 202, in set_program
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Service set_program: 400 Bad Request
```

**Comment by astrandb** [comment]
Error 400 is often seen when the Miele API does not like the command. Can be due to a missing precondition or unknown program Id or whatever...
Please set your washer to remote control, close the door and so on. Then capture a diagnostic download from the device overview page for you washing machine and upload to this issue.

**Comment by koburg** [comment]
file attached
[miele-634be6fba1bee63983b5c3937a7d4970-Washing machine-eb43e0b5295bc0dc0c430ebce37e4136.json.txt](https://github.com/astrandb/miele/files/8514982/miele-634be6fba1bee63983b5c3937a7d4970-Washing.machine-eb43e0b5295bc0dc0c430ebce37e4136.json.txt)

**Comment by astrandb** [comment]
The relevant part of the diagnostics dump shows that your device will not accept any commands from the API -` processAction` is empty. The only command that is accepted at the moment is `powerOff`.

```json
    "actions": {
      "processAction": [],
      "light": [],
      "ambientLight": [],
      "startTime": [],
      "ventilationStep": [],
      "programId": [],
      "targetTemperature": [],
      "deviceName": true,
      "powerOn": false,
      "powerOff": true,
      "colors": [],
      "modes": []
    },
```
I recommend that you experiment with [Swagger](https://www.miele.com/developer/swagger-ui/) on Miele´s development site to find out why you are not allowed to send commands to your device.

**Comment by koburg** [comment]
Thanks!

I have been testing swagger and if I try to GET programs that are avail I get all the known programs with id numbers.
but the action call I get same list as the one from the diag file.

and all PUT commands give me 400 error.

my account on Miele is setup to Denmark Da don't know if there is an issue with this localisation.

Also im able to use the **MIELE IOS APP** and can do all changes I want so don't get it why the swagger don't work.
maybe firmware or swagger issue with this model.

**Comment by astrandb** [comment]
OK, The public API/Swagger is something different than the internal API used for the IOS and Android apps. If you cannot make the PUT requests work with Swagger, neither can the HA integration unfortunately. 
You could ask at developer@miele.com why you cannot conttrol your appliance via Swagger. Sometimes they answer...

**Comment by ArnoutVos** [comment]
Same problem over here, difference is that "programs" collection is giving a 400 already:

[miele-892fedfe2bd3787483747a7716668905-Washing machine-d3e1be73dac4f2b47fcc5169272c30e0.json.txt](https://github.com/astrandb/miele/files/9764170/miele-892fedfe2bd3787483747a7716668905-Washing.machine-d3e1be73dac4f2b47fcc5169272c30e0.json.txt)

The diag file is captured when the device is ready to run. I selected a program via the Miele android app, and that appears to be programId 52, but when I use 52 in my request, a 400 is given.

```
service: miele.set_program
data:
  programId: 31
target:
  device_id: d3e1be73dac4f2b47fcc5169272c30e0
```

**Comment by astrandb** [comment]
The issue was closed because the problem is in Miele's end. If you cannot make it work from Swagger, it will not work in the integration. Unfortunately there is a mismatch between the internal API Miele is using for their own apps and the API they publish for public use.
