### ISSUE TITLE
NoURLAvailableError when

### ISSUE THREAD

**Issue by vk496** [astrandb/miele#89]
### The problem

After installing HACS and configuring `configuration.yaml`, I don't have a Integration (rebooted HA). In the logs of the Core I have this message:

```
ERROR (MainThread) [homeassistant.setup] Error during setup of component miele
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/miele/__init__.py", line 124, in async_setup
    network.get_url(hass, allow_external=True, prefer_external=True),
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 168, in get_url
    request_host = _get_request_host()
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 207, in _get_request_host
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
```

### Version of miele integration having the issue?

v0.0.20

### Version of Home Assistant Core having the issue?

2022.4.6

**Comment by vk496** [comment]
Seems to be related with DuckDNS, This solved the issue in the other integration: https://github.com/HomeAssistant-Mods/home-assistant-miele/issues/65#issuecomment-923386156

**Comment by astrandb** [comment]
>File "/config/custom_components/miele/__init__.py", line 124, in async_setup
    network.get_url(hass, allow_external=True, prefer_external=True)
This part from the log shows clearly that the error comes from "the other" integration.
Make sure that you delete all files from that integration before installing this one.

**Comment by vk496** [comment]
Thnks @astrandb . Is really weird, since I made sure to restart HA between each un/install. In any case, since the Miele Oauth login require a HA url callback (at least something I guess), installing DuckDNS integration to have https may unset that URL (didn't verified), which caused this kind of error.

Anyways, thnks for you integration. Having a logical organization per device is quite better and more integrated with HA than just single entities of the other one.

Have a nice day,
Valentín
