### ISSUE TITLE
No devices discovered

### ISSUE THREAD

**Issue by arief1986** [astrandb/miele#93]
### The problem

After successful authorization, no devices are detected through the integration. The devices are visible though the Miele Swagger-UI with the same Client_ID and Client_Secret. No errors are generated in the log, but the diagnostics file display the devices and its attributes correctly (see attachment:

[config_entry-miele-448c31f5a9b474550c6833e12ade258d.json.txt](https://github.com/astrandb/miele/files/8651483/config_entry-miele-448c31f5a9b474550c6833e12ade258d.json.txt)

It is however not added as a device / entity. 

### Version of miele integration having the issue?

0.0.19

### Version of Home Assistant Core having the issue?

2022.5.3

**Comment by astrandb** [comment]
@arief1986  It is a simple task to just add the device with some generic status sensors. However, you are the first integration user that has access to an induction hob. I will need some help with ideas/tests/verifications when implementing control entities for the cooker plates.

**Comment by arief1986** [comment]
Many thanks for your quick response! Yes, that's indeed the induction model with an integrated extraction fan. Happy to do some more scenarios and extract the diagnostic dumps if that helps.

I've put a kettle on various plates and played with the induction power and fan speed a bit. It seems that many states are read correctly. 

- For induction power (plateStep), "value_localized" is indeed the set induction power (0 to 9; and "Boost\u00a01" for boost); and are read for each zones correctly. 
- For fan speed, "value_localized" is the correct speed (0 to 3; and "B" for boost)
- Hob status is displayed in "state|status|value_localized", either "Off" or "In Use" 

I have attached the diagnostics dumps. Thanks for your help!
[config_entry-miele-448c31f5a9b474550c6833e12ade258d.json-2.txt](https://github.com/astrandb/miele/files/8652459/config_entry-miele-448c31f5a9b474550c6833e12ade258d.json-2.txt)
[config_entry-miele-448c31f5a9b474550c6833e12ade258d.json-3.txt](https://github.com/astrandb/miele/files/8652460/config_entry-miele-448c31f5a9b474550c6833e12ade258d.json-3.txt)
[config_entry-miele-448c31f5a9b474550c6833e12ade258d.json-4.txt](https://github.com/astrandb/miele/files/8652461/config_entry-miele-448c31f5a9b474550c6833e12ade258d.json-4.txt)
[config_entry-miele-448c31f5a9b474550c6833e12ade258d.json-5.txt](https://github.com/astrandb/miele/files/8652462/config_entry-miele-448c31f5a9b474550c6833e12ade258d.json-5.txt)
[config_entry-miele-448c31f5a9b474550c6833e12ade258d.json-6.txt](https://github.com/astrandb/miele/files/8652463/config_entry-miele-448c31f5a9b474550c6833e12ade258d.json-6.txt)

**Comment by astrandb** [comment]
Thank you. Can you please list the pairs of `value_raw` and `value_localized` for `plateSteps`. I use `value_raw` in the integration 
in all other device types since it is more reliable across the supported languages.

I am not very hopeful that it is possible to control the settings through the API. The `actions` response indicates what actions and settings that are available at each specific moment. All parameters are empty or false which marks that nothing can be altered just now. Is there a setting on the physical device to enable remote control?

**Comment by arief1986** [comment]
Thanks! See the list of pairs below:

value_localized: 0  / value_raw: 0
value_localized: 1  / value_raw: 1
value_localized: 2  / value_raw: 3
value_localized: 3  / value_raw: 5
value_localized: 4  / value_raw: 7
value_localized: 5  / value_raw: 9
value_localized: 6  / value_raw: 11
value_localized: 7  / value_raw: 13
value_localized: 8  / value_raw: 15
value_localized: 9  / value_raw: 17
value_localized: Boost\u00a01  / value_raw: 117

I think you are right with regards to the "actions". This does not seem to be possible in the official Miele app either, so it's probably read only for this device (which makes sense for a hood).

Let me know if you need more tests / diagnostics.
