### ISSUE TITLE
Add KickoffTime and FinishTime

### ISSUE THREAD

**Issue by gigatexel** [astrandb/miele#94]
### Feature request

I would like to get these additional sensors/attributes in this new (and better) integration that were also available in the old(er) integration by kloknibor

Kickofftime = now - elapsedTime
FinishTime = now + remainingTime

This could be usefull for multiple types of devices

Offcourse, you can create custom templates but integrating this might be more elegant.

See https://github.com/HomeAssistant-Mods/home-assistant-miele/blob/master/custom_components/miele/sensor.py#L587

### What version of the integration are you using?

0.0.20

**Comment by mundschenk-at** [comment]
Please have a look at the discussion [here](https://github.com/astrandb/miele/discussions/37).

**Comment by gigatexel** [comment]
Thank you for making this possible!

![image](https://user-images.githubusercontent.com/65073191/171396278-dc1c9be4-01dd-435f-b8b3-783e43027004.png)
