### ISSUE TITLE
Water and energy consumption unavailable

### ISSUE THREAD

**Issue by davidmh78** [astrandb/miele#96]
### The problem

Hello, the water and energy consumption of a Miele washing machine are not available in this integration, although works fine in the old / other integration. But as this integration correctly reports a lot of info that the other doesn't (washing cycle, rpm, etc) therefore is better, any ideas on how to get those water/energy values?

thanks

<img width="347" alt="image" src="https://user-images.githubusercontent.com/52571539/169325133-fc5914c8-3867-4823-b13b-0beea894c003.png">

### Version of miele integration having the issue?

miele-0.0.20

### Version of Home Assistant Core having the issue?

core-2022.5.4

**Comment by astrandb** [comment]
I see on your screen dump that the sensor might be disabled. Dive into `Advanced settings` and enable the sensor, wait for 30 sec and refresh the screen.

**Comment by davidmh78** [comment]
You're right, that was it. Totally my fault, sorry and thanks!
